Update source/.bashrc.d/20_alias
Former-commit-id: 553c394db29c6c6b60d22cd75f9046b878cf9b5c
Former-commit-id: 9b41a8425ea276f6db83024a2cbfcf9437e96c0a
Former-commit-id: 967fd406caa7c1478d192c155e3044284be48205

diff --git a/source/exact_dot_bashrc.d/20_alias b/source/exact_dot_bashrc.d/20_alias
--- a/source/exact_dot_bashrc.d/20_alias
+++ b/source/exact_dot_bashrc.d/20_alias
@@ -141,3 +141,20 @@ fi
 # alias start-gdm='sudo systemctl start gdm.service'
 alias start-gdm="systemctl isolate graphical.target"
 alias stop-gdm="systemctl isolate multi-user.target"
+function visual() {
+  local wm=$1 wmpath
+  local server=$2
+
+  if [ -z "$wm" ]; then wm="x-window-manager"; fi
+  if ! wmpath=$(which "$wm"); then
+    printf '%s\n' "Unable to find $wm in \$PATH" >&2
+    return 2
+  fi
+  regex="^:[[:digit:]]+"
+  if [[ $server =~ $regex ]]; then
+    xinit "$wmpath" -- "$@"
+  else
+    xinit "$wmpath" "$@"
+  fi
+}
+alias visual="startx \$(which awesome) --"
