Update source/.bashrc.d/999_Prompt-Exit-Code Update source/.bashrc.d/60_PS1/00_git Update source/.bashrc.d/60_PS1/999_truncate
Former-commit-id: b53a42101eba9b90e71dec36bb80c0dc5cdac86a
Former-commit-id: f49cf8270afca48a7bfed32fb8221b9e4fae1774
Former-commit-id: 1f4e7e4bd80cf78f0dfbeb2d56d1d8e36c42bd86

diff --git a/source/exact_dot_bashrc.d/999_Prompt-Exit-Code b/source/exact_dot_bashrc.d/999_Prompt-Exit-Code
--- a/source/exact_dot_bashrc.d/999_Prompt-Exit-Code
+++ b/source/exact_dot_bashrc.d/999_Prompt-Exit-Code
@@ -12,5 +12,10 @@
 # Ensure prompt command ends with a ;
 old_prompt="${PROMPT_COMMAND:+${PROMPT_COMMAND/%;/};}"
 
-# Capture exit code before prompt and reinstantiate after
-PROMPT_COMMAND='__EXIT="$?";'"$old_prompt"'(exit $__EXIT)'
+pre='__EXIT=$?;'
+# shellcheck disable=SC2016 # IK expressions do not expand. that is the point.
+post='(exit $__EXIT)'
+if ! [[ "${PROMPT_COMMAND:-}" == "$pre"*"$post" ]]; then
+	# Capture exit code before prompt and reinstantiate after
+	PROMPT_COMMAND="$pre$old_prompt$post"
+fi
diff --git a/source/exact_dot_bashrc.d/exact_60_PS1/00_git b/source/exact_dot_bashrc.d/exact_60_PS1/00_git
--- a/source/exact_dot_bashrc.d/exact_60_PS1/00_git
+++ b/source/exact_dot_bashrc.d/exact_60_PS1/00_git
@@ -46,131 +46,136 @@ export GIT_PS1_LONG_LENGTH=90
 
 # Check if we support colors
 __color_enabled() {
-  local -i colors
-  colors=$(tput colors 2>/dev/null)
-  # shellcheck disable=SC2181
-  [[ $? -eq 0 ]] && [[ $colors -gt 2 ]]
+	local -i colors
+	colors=$(tput colors 2>/dev/null)
+	# shellcheck disable=SC2181
+	[[ $? -eq 0 ]] && [[ $colors -gt 2 ]]
 }
 unset __colorize_prompt && __color_enabled && __colorize_prompt=1
 
 __set_bash_prompt() {
-  # Desired result:
-  #  Color: ${yellow}jobs${none}|${red}HH:MM|${bGre}USERNAME@HOST${none}:${blue}SHORTPATH${none}(GIT)${red}ERROR${none}$
-  #  White: \j|\D{%I:%M%P}|\u@\h:\w(GIT)\$
-  local exit=${__EXIT:-"$?"} # Save the exit status of the last command
+	# Desired result:
+	#  Color: ${yellow}jobs${none}|${red}HH:MM|${bGre}USERNAME@HOST${none}:${blue}SHORTPATH${none}(GIT)${red}ERROR${none}$
+	#  White: \j|\D{%I:%M%P}|\u@\h:\w(GIT)\$
+	local exit=${__EXIT:-"$?"} # Save the exit status of the last command
 
-  # PS1 is made from $PreGitPS1 + <git-status> + $PostGitPS1
+	# PS1 is made from $PreGitPS1 + <git-status> + $PostGitPS1
 
-  # Track if git is installed
-  local git_available=''
-  if { command -v git && git --version; } &>/dev/null; then
-    git_available=1
-  fi
+	# Track if git is installed
+	local git_available=''
+	if { command -v git && git --version; } &>/dev/null; then
+		git_available=1
+	fi
 
-  # Create (GIT: TOP-LEVEL) for titlebar
-  local gitString=""
-  if [[ $git_available ]] && git rev-parse &>/dev/null; then # In git
-    gitString=" (GIT: "
-    if [[ "$(git rev-parse --is-inside-work-tree)" = "true" ]]; then # In work tree
-      gitString+=$(basename -- "$(git rev-parse --show-toplevel 2>/dev/null)")
-    else # In .git
-      gitString+=$(basename -- "$(realpath -- "$(git rev-parse --git-dir)/..")")
-    fi
-    gitString+=")"
-  fi
+	# Create (GIT: TOP-LEVEL) for titlebar
+	local gitString=""
+	if [[ $git_available ]] && git rev-parse &>/dev/null; then # In git
+		gitString=" (GIT: "
+		if [[ "$(git rev-parse --is-inside-work-tree)" = "true" ]]; then # In work tree
+			gitString+=$(basename -- "$(git rev-parse --show-toplevel 2>/dev/null)")
+		else # In .git
+			gitString+=$(basename -- "$(realpath -- "$(git rev-parse --git-dir)/..")")
+		fi
+		gitString+=")"
+	fi
 
-  # Escapes for setting titlebar
-  local title='\[\e]0;' end='\a\]'
-  # Titlebar
-  local TitleBar="$title\W$gitString: \u$end\${debian_chroot:+(\$debian_chroot)}"
-  unset gitString end title
+	# Escapes for setting titlebar
+	local title='\[\e]0;' end='\a\]'
+	# Titlebar
+	local TitleBar="$title\W$gitString: \u$end\${debian_chroot:+(\$debian_chroot)}"
+	unset gitString end title
 
-  # Variables to set depending on $COLUMNS
-  local ShortPS1="" LongPS1=""
+	# Variables to set depending on $COLUMNS
+	local ShortPS1="" LongPS1=""
 
-  if [[ $__colorize_prompt ]]; then
-    export GIT_PS1_SHOWCOLORHINTS=1
-    # Wrap the color codes between \[ and \], so that
-    # bash counts the correct number of characters for line wrapping:
-    {
-      local Red='\[\e[0;31m\]' BRed='\[\e[1;31m\]' Gre='\[\e[0;32m\]' BGre='\[\e[1;32m\]'
-      local Yel='\[\e[0;33m\]' BYel='\[\e[1;33m\]' Blue='\[\e[0;34m\]' BBlue='\[\e[1;34m\]'
-      local Mag='\[\e[0;35m\]' BMag='\[\e[1;35m\]' Cya='\[\e[0;36m\]' BCya='\[\e[1;36m\]'
-      local Whi='\[\e[0;37m\]' BWhi='\[\e[1;37m\]' None='\[\e[0m\]'
-    }
-  else # No color
-    # unset all the colors so they don't show
-    unset GIT_PS1_SHOWCOLORHINTS
-    # shellcheck disable=SC2034
-    {
-      local Red='' BRed='' Gre='' BGre=''
-      local Yel='' BYel='' Blue='' BBlue=''
-      local Mag='' BMag='' Cya='' BCya=''
-      local Whi='' BWhi='' None=''
-    }
-  fi
+	if [[ $__colorize_prompt ]]; then
+		export GIT_PS1_SHOWCOLORHINTS=1
+		# Wrap the color codes between \[ and \], so that
+		# bash counts the correct number of characters for line wrapping:
+		{
+			local Red='\[\e[0;31m\]' BRed='\[\e[1;31m\]' Gre='\[\e[0;32m\]' BGre='\[\e[1;32m\]'
+			local Yel='\[\e[0;33m\]' BYel='\[\e[1;33m\]' Blue='\[\e[0;34m\]' BBlue='\[\e[1;34m\]'
+			local Mag='\[\e[0;35m\]' BMag='\[\e[1;35m\]' Cya='\[\e[0;36m\]' BCya='\[\e[1;36m\]'
+			local Whi='\[\e[0;37m\]' BWhi='\[\e[1;37m\]' None='\[\e[0m\]'
+		}
+	else # No color
+		# unset all the colors so they don't show
+		unset GIT_PS1_SHOWCOLORHINTS
+		# shellcheck disable=SC2034
+		{
+			local Red='' BRed='' Gre='' BGre=''
+			local Yel='' BYel='' Blue='' BBlue=''
+			local Mag='' BMag='' Cya='' BCya=''
+			local Whi='' BWhi='' None=''
+		}
+	fi
 
-  local pipe="${None}|"
-  # Jobs and time
-  LongPS1+="$Yel\j$pipe$BRed\D{%I:%M}$pipe"
-  # Bright color if root
-  if [[ ${EUID} -gt 0 ]]; then
-    LongPS1+="${BGre}"
-    ShortPS1+="${BGre}"
-  else
-    LongPS1+="${BMag}"
-    ShortPS1+="${BMag}"
-  fi
-  # User@Host Colon and path
-  LongPS1+="\u@\h$None:$BBlue\\w$None"
-  ShortPS1+="\u$None:$BBlue\\w$None"
+	local pipe="${None}|"
+	# Jobs and time
+	LongPS1+="$Yel\j$pipe$BRed\D{%I:%M}$pipe"
+	# Bright color if root
+	if [[ ${EUID} -gt 0 ]]; then
+		LongPS1+="${BGre}"
+		ShortPS1+="${BGre}"
+	else
+		LongPS1+="${BMag}"
+		ShortPS1+="${BMag}"
+	fi
+	# User@Host Colon and path
+	LongPS1+="\u@\h$None:$BBlue\\w$None"
+	ShortPS1+="\u$None:$BBlue\\w$None"
 
-  # Set to LongPS1 if greater than GIT_PS1_LONG_LENGTH, else ShortPS1
-  local PreGitPS1=""
-  if [[ $COLUMNS -gt ${GIT_PS1_LONG_LENGTH:-90} ]]; then
-    PreGitPS1=$TitleBar$LongPS1
-  else
-    PreGitPS1=$TitleBar$ShortPS1
-  fi
-  unset LongPS1 ShortPS1
+	# Set to LongPS1 if greater than GIT_PS1_LONG_LENGTH, else ShortPS1
+	local PreGitPS1=""
+	if [[ $COLUMNS -gt ${GIT_PS1_LONG_LENGTH:-90} ]]; then
+		PreGitPS1=$TitleBar$LongPS1
+	else
+		PreGitPS1=$TitleBar$ShortPS1
+	fi
+	unset LongPS1 ShortPS1
 
-  # Now build the part after git's status
-  PostGitPS1=""
+	# Now build the part after git's status
+	PostGitPS1=""
 
-  # Highlight non-standard exit codes
-  if [[ $exit -ne 0 ]]; then
-    PostGitPS1+="${Red}[$exit]"
-  fi
+	# Highlight non-standard exit codes
+	if [[ $exit -ne 0 ]]; then
+		PostGitPS1+="${Red}[$exit]"
+	fi
 
-  # Change color of prompt if root
-  if [[ ${EUID} == 0 ]]; then
-    PostGitPS1+="$BRed"'\$ '
-  else
-    PostGitPS1+="$None"'\$ '
-  fi
-  PostGitPS1+="$None"
+	# Change color of prompt if root
+	if [[ ${EUID} == 0 ]]; then
+		PostGitPS1+="$BRed"'\$ '
+	else
+		PostGitPS1+="$None"'\$ '
+	fi
+	PostGitPS1+="$None"
 
-  # Prepare __git_ps1 for calling
+	# Prepare __git_ps1 for calling
 
-  # Add - before branch if current directory is ignored
-  local ignored
-  if [[ $git_available ]]; then
-    ignored=$(git check-ignore -q . &>/dev/null && echo -n "${Red}-")
-  fi
-  # Ensure __git_ps1 is accessible, set PS1 and
-  # reset this function if not
-  if ! command -v __git_ps1 &>/dev/null; then
-    PS1=$PreGitPS1$PostGitPS1
-    return
-  fi
+	# Add - before branch if current directory is ignored
+	local ignored
+	if [[ $git_available ]]; then
+		ignored=$(git check-ignore -q . &>/dev/null && echo -n "${Red}-")
+	fi
+	# Ensure __git_ps1 is accessible, set PS1 and
+	# reset this function if not
+	if ! command -v __git_ps1 &>/dev/null; then
+		PS1=$PreGitPS1$PostGitPS1
+		return
+	fi
 
-  # Set PS1 from $PreGitPS1 + <git-status> + $PostGitPS1
-  __git_ps1 "$PreGitPS1" "$PostGitPS1" "($ignored%s)"
+	# Set PS1 from $PreGitPS1 + <git-status> + $PostGitPS1
+	__git_ps1 "$PreGitPS1" "$PostGitPS1" "($ignored%s)"
 
-  # defaut Linux Mint 17.2 user prompt:
-  # PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\] $(__git_ps1 "(%s)") \$ '
+	# defaut Linux Mint 17.2 user prompt:
+	# PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[01;34m\] \w\[\033[00m\] $(__git_ps1 "(%s)") \$ '
+	return "$exit"
 }
 
 # This tells bash to reinterpret PS1 after every command, which we
 # need because __git_ps1 will return different text and colors
+
+if [[ "${PROMPT_COMMAND:-}" == *"__set_bash_prompt"* ]]; then
+	return 0
+fi
 PROMPT_COMMAND="${PROMPT_COMMAND:+${PROMPT_COMMAND/%;/};}"'__set_bash_prompt'
