save n to tmpfile and run as sudo
Run as sudo to avoid having user owned files in /usr/local

saved to a file to keep curl issues from being executed in bash

diff --git a/source/.chezmoiscripts/install/run_onchange_after_10-pnpm.sh.tmpl b/source/.chezmoiscripts/install/run_onchange_after_10-pnpm.sh.tmpl
--- a/source/.chezmoiscripts/install/run_onchange_after_10-pnpm.sh.tmpl
+++ b/source/.chezmoiscripts/install/run_onchange_after_10-pnpm.sh.tmpl
@@ -20,19 +20,17 @@ function add_global_dir_to_path() {
 }
 
 function install_pnpm_and_node() {
-  sudo -v
-  # Setup n
-  log 'Setting up /usr/local files for n'
-  local files=(/usr/local/{bin,lib/node_modules,include,share/{,man},n})
-  sudo mkdir -p "${files[@]}"
-  sudo chown -R "$(whoami)" "${files[@]}"
-
+  local tmp=$(mktmp)
+  trap 'rm -f "$tmp"' EXIT
+  log 'installing n'
+  curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n -o "$tmp"
   log 'installing node lts through n...'
   (
+    export -n SHELLOPTS
     # NOTE: latest is needed on my machine to avoid EHOSTUNREACH from npm repos
-    export -n SHELLOPTS &&
-      curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n | /usr/bin/env bash -s -- latest
+    sudo bash "$tmp" latest
   )
+  rm -f "$tmp" && trap '' EXIT # cleanup
 
   # Setup pnpm
   log 'installing pnpm'
