Update source/.root/etc/grub.d/11_custom_text_mode
Former-commit-id: 6856da5f9e9998f648cc384be4a6dc466208a4ec
Former-commit-id: 26452c35e054a05f9eb395e8fdd3c3f6454fd50d
Former-commit-id: 6ec64ef48592195e9437844480bc5abb3acba39c

diff --git a/source/exact_dot_root/exact_etc/exact_grub.d/executable_11_custom_text_mode b/source/exact_dot_root/exact_etc/exact_grub.d/executable_11_custom_text_mode
--- a/source/exact_dot_root/exact_etc/exact_grub.d/executable_11_custom_text_mode
+++ b/source/exact_dot_root/exact_etc/exact_grub.d/executable_11_custom_text_mode
@@ -1,8 +1,10 @@
 #!/bin/sh
-set -e
+set -euC
+# log to stderr bc stdout is to grub
 log() { printf '%s\n' "$@" >&2; }
+err() { printf '%s\n' "$@" >&2; }
 abort() {
-  log "$@"
+  log "$1"
   exit 1
 }
 
@@ -24,6 +26,14 @@ find_highest_version() {
 
 VMLINUZ=$(find_highest_version /boot 'vmlinuz-*-generic')
 INITRD=$(find_highest_version /boot 'initrd.img-*-generic')
+# Fallbacks - desperately try to find one.
+if [ -z "$VMLINUZ" ]; then VMLINUZ=$(printf '%s\0' /boot/vmlinuz* | head -zn1 | tr -d '\0'); fi
+if [ -z "$INITRD" ]; then INITRD=$(printf '%s\0' /boot/initrd.img* | head -zn1 | tr -d '\0'); fi
+
+# ABORT ABORT
+if [ -z "$VMLINUZ" ]; then abort "Could not find vmlinuz"; fi
+if [ -z "$INITRD" ]; then abort "Could not find initrd.img"; fi
+
 # Remove splash and quiet args from GRUB_CMDLINE_LINUX_DEFAULT
 GRUB_CMDLINE_ARGS=$(printf '%s\n' "$GRUB_CMDLINE_LINUX_DEFAULT" | sed -e 's/\bsplash\b//g' -e 's/\bquiet\b//g')
 
