Update source/.local/bin/brightness

diff --git a/source/dot_local/exact_bin/executable_brightness b/source/dot_local/exact_bin/executable_brightness
--- a/source/dot_local/exact_bin/executable_brightness
+++ b/source/dot_local/exact_bin/executable_brightness
@@ -1,8 +1,6 @@
 #!/usr/bin/env bash
-
 set -euC -o pipefail
-
-THIS="brightness"
+. script_utils.sh || exit
 
 function usage() {
   cat || true <<-EOF
@@ -21,29 +19,15 @@ Options:
 EOF
 }
 
-function log() { printf '%s\n' "$@" || true; }
-function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
-function abort() { err "$1" && exit "${2:-1}"; }
-number_re='^[0-9]+$'
-function is_integer() { [[ "$1" =~ $number_re ]]; }
-
-# Returns a string that should be 'eval'ed to set the positional arguments
-# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
-# Input: $LONGOPTS,$SHORTOPTS
-# eval "$(parse_args "$@")"
-function parse_args() {
-  local parsed
-  local code=0 && getopt --test &>/dev/null || code=$?
-  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
-  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
-    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
-  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
+function is_integer() {
+  local number_re='^[0-9]+$'
+  [[ "$1" =~ $number_re ]]
 }
 
 LONGOPTS="help,device:" SHORTOPTS="h,d:"
-ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
+eval "$(parse_args "$@")" || exit
 
-device=''
+device='' show=0
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
@@ -52,45 +36,36 @@ while true; do
   *) abort "This is a bug" 3 ;;
   esac
 done
-show=false
-if [ "$#" -eq 0 ]; then show="true"; fi
+[ "$#" -gt 0 ] || show=1
 
 BrPath="$device"
-if [ -z "$BrPath" ]; then
-  BrPath="$(find /sys/class/backlight -maxdepth 1 -mindepth 1 -print0 | head -zn1 | tr -d '\0')"
-fi
+[ -n "$BrPath" ] || BrPath="$(find /sys/class/backlight -maxdepth 1 -mindepth 1 -print0 | head -zn1 | tr -d '\0')"
 
-if [ -z "$BrPath" ]; then
-  abort "Unable to find backlight device" 1
-elif ! [ -d "$BrPath" ]; then
-  abort "Found backlight device is not a directory" 1
-elif ! [ -f "$BrPath/max_brightness" ]; then
-  abort "Backlight device must support /max_brightness" 1
-elif ! [ -f "$BrPath/brightness" ]; then
-  abort "Backlight device must support /brightness" 1
-fi
+[ -n "$BrPath" ] || abort "Unable to find backlight device" 1
+[ -d "$BrPath" ] || abort "Found backlight device is not a directory" 1
+[ -f "$BrPath/max_brightness" ] || abort "Backlight device must support /max_brightness" 1
+[ -f "$BrPath/brightness" ] || abort "Backlight device must support /brightness" 1
 
-BrMax="$(<"$BrPath/max_brightness")"
-if ! is_integer "$BrMax"; then abort "Invalid max brightness '$BrMax'" 2; fi
-BrCur="$(<"$BrPath/brightness")"
-if ! is_integer "$BrCur"; then abort "Invalid current brightness '$BrCur'" 2; fi
+BrMax="$(<"$BrPath/max_brightness")" BrCur="$(<"$BrPath/brightness")"
+is_integer "$BrMax" || abort "Invalid max brightness '$BrMax'" 2
+is_integer "$BrCur" || abort "Invalid current brightness '$BrCur'" 2
 declare -i BrMax BrMax BrCur # Cast all to integers
 # 100th max-brightness, rounded up to nearest integer
 BrMin="$((0 + (BrMax + 100 - 1) / 100))"
 
-if [ "$BrMax" -eq 0 ]; then abort "Backlight device reported maximum brightness of 0." 1; fi
+[ "$BrMax" -ne 0 ] || abort "Backlight device reported maximum brightness of 0." 1
 
 BrCurRel="$(printf '%s ' "$BrCur" "$BrMax" | awk '{ print int( $1 / $2 * 100 ) }')"
 
-if [ "$show" = true ]; then log "$BrCurRel" && exit 0; fi
+[ "$show" -eq 0 ] || { log "$BrCurRel" && exit 0; }
 
-BrNewRel="${1:-}" && if [ -z "$BrNewRel" ]; then abort "Brightness can't be empty" 2; fi
+{ BrNewRel="${1:-}" && [ -n "$BrNewRel" ]; } || abort "Brightness can't be empty" 2
 suf='' && case "$BrNewRel" in
 +* | *+) suf=+ ;;
 -* | *-) suf=- ;;
 esac
 BrNewRel=${BrNewRel%-} BrNewRel=${BrNewRel#-} BrNewRel=${BrNewRel%+} BrNewRel=${BrNewRel#+} BrNewRel=${BrNewRel%\%}
-if ! is_integer "$BrNewRel"; then abort "Invalid brightness '$BrNewRel'" 2; fi
+is_integer "$BrNewRel" || abort "Invalid brightness '$BrNewRel'" 2
 case "$suf" in
 +) BrNewRel=$((BrCurRel + BrNewRel)) ;;
 -) BrNewRel=$((BrCurRel - BrNewRel)) ;;
@@ -100,7 +75,8 @@ BrNew="$(printf '%s ' "$BrNewRel" "$BrMax" | awk '{ print int( ( ($1/100) * $2) 
 BrNew="$((BrNew < BrMin ? BrMin : BrNew))"
 BrNew="$((BrNew > BrMax ? BrMax : BrNew))"
 
-sudo=()
-if ! [ -w "$BrPath"/brightness ]; then sudo=("${SUDO:-sudo}"); fi
-
-printf '%s' "$BrNew" | "${sudo[@]}" tee "$BrPath/brightness" >/dev/null
+if [ -w "$BrPath/brightness" ]; then
+  printf '%s' "$BrNew" >|"$BrPath/brightness"
+else
+  printf '%s' "$BrNew" | sudo_cmd tee "$BrPath/brightness" >/dev/null
+fi
