Update source/.local/bin/update-java
Former-commit-id: 81f3b3f2c0c4b510c745ba5580d4749f0fef60bb
Former-commit-id: d090031a2b2279f1c4c6e4d96858478cebed3d63
Former-commit-id: b87eae3e15fb5b511786aa8c98d5b81f7f4372dd

diff --git a/source/dot_local/exact_bin/executable_update-java b/source/dot_local/exact_bin/executable_update-java
--- a/source/dot_local/exact_bin/executable_update-java
+++ b/source/dot_local/exact_bin/executable_update-java
@@ -4,25 +4,65 @@
 #
 # Updates java symlinks to the path specified using update-alternatives
 #
+set -euC -o pipefail
 
-if [ "$1" = --help ] || [ "$#" -eq 0 ]; then
-  cat <<-EOF
-  update-java [-y | --yes] <JAVADIR> [priority = 1112] [JVM_VERS_DIR]
-  Updates java symlinks to the path specified using update-alternatives.
-  Do not include /bin on JAVADIR.
-  JVM_VERS_DIR will be determined by JAVA_HOME if set, or else default to /usr/lib/jvm
+THIS=update-java
+usage() {
+  cat <<EOF
+$THIS [-y | --yes] <JAVADIR> [priority = 1112] [JVM_VERS_DIR]
+Updates java symlinks to the path specified using update-alternatives.
+Do not include /bin on JAVADIR.
+JVM_VERS_DIR will be determined by JAVA_HOME if set, or else default to /usr/lib/jvm
 EOF
-  [ "$#" -eq 0 ] && exit 2 || exit 0
-fi
-yes=0
-if [ "$1" = --yes ] || [ "$1" = -y ]; then
-  yes=1 && shift
-fi
+  EOF
+  return 0
+}
 
-JAVADIR=$1
+log() { printf '%s\n' "$@"; }
+err() { printf "${THIS:-$0}: %s\n" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
+
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+
+LONGOPTS=help,yes
+SHORTOPTS=h,y
+ARGSTRING="$(parse_args "$@")"
+eval "$ARGSTRING"
+
+yes=0
+while true; do
+  case "$1" in
+  -h | --help) usage && exit 0 ;;
+  -y | --yes) yes=1 && shift ;;
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
+  esac
+done
+if [ "$#" -eq 0 ]; then usage && exit 2; fi
+
+JAVADIR=${1:-}
 PRIORITY=${2:-1112}
 BINDIR=/usr/bin
-if [[ -n "$3" ]]; then
+if [[ -n "${3:-}" ]]; then
   JVM_VERS_DIR=$3
 elif [[ -n "$JAVA_HOME" ]]; then
   JVM_VERS_DIR=$(dirname -- "$JAVA_HOME") # /usr/lib/jvm/jdk-version --> /usr/lib/jvm
@@ -30,54 +70,49 @@ else
   JVM_VERS_DIR=/usr/lib/jvm
 fi
 
-if ! [[ -d "$JVM_VERS_DIR" ]]; then
-  printf 'warning: "%s" is not a directory. It will be created on confirmation\n' "$JVM_VERS_DIR" >&2
+if ! [ -d "$JVM_VERS_DIR" ]; then
+  err "'$JVM_VERS_DIR' is not a directory. It will be created on confirmation" "$JVM_VERS_DIR"
 fi
 
-if ! [[ -d "$JAVADIR" ]]; then
-  printf '"%s" is not a directory\n' "$JAVADIR" >&2
-  exit 2
-else
-  JAVADIR=$(realpath -- "$JAVADIR")
-fi
+if ! [ -d "$JAVADIR" ]; then abort "'$JAVADIR' is not a directory\n" 2; fi
+JAVADIR=$(realpath -- "$JAVADIR")
 
 if [[ "$JAVADIR" =~ ?(.*)/bin$ ]]; then
-  if [ $yes -ne 1 ]; then
+  if [ "$yes" -eq 1 ]; then confirmation=yes; else
     read -rep "$JAVADIR ends in /bin, would you like to use it's parent? (yes) " confirmation >&2
-  else
-    confirmation=yes
   fi
   if [[ -z "$confirmation" || "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
     JAVADIR=$(dirname -- "$(realpath -- "$JAVADIR")")
   fi
 fi
 
-if [ $yes -ne 1 ]; then
+if ! [ "$yes" -eq 1 ]; then
   read -rep "Are you sure you would like to link all binaries in $JAVADIR? (yes) " confirmation
   if [[ -n "$confirmation" && ! "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
-    printf '%s\n' "Aborting" >&2
-    exit 1
+    abort "Aborting" 1
   fi
 fi
 
 # Update sudo timestamp
-sudo --validate || exit
+sudo --validate
 
 sudo mkdir -p "$JVM_VERS_DIR"
 JVM_VERS_DIR=$(realpath -- "$JVM_VERS_DIR")
 
 if [[ $(dirname -- "$JAVADIR") != "$JVM_VERS_DIR" ]]; then
   printf 'Copying files to "%s"\n' "$JVM_VERS_DIR" >&2
-  sudo -E -H cp --archive --interactive "$JAVADIR" "$JVM_VERS_DIR"
+  sudo -E -H -- cp --archive --interactive "$JAVADIR" "$JVM_VERS_DIR"
   JAVADIR="$JVM_VERS_DIR/$(basename -- "$JAVADIR")"
 fi
 
-find "$JAVADIR" -perm /u=x,g=x,o=x -type f -print0 | while read -d $'\0' -sr FP; do
+while read -d $'\0' -sr FP; do
   FN=$(basename -- "$FP")
   printf '%s\n' "update-alternatives --install \"$BINDIR/$FN\" \"$FN\" \"$FP\" \"$PRIORITY\""
   sudo -E -H update-alternatives --install "$BINDIR/$FN" "$FN" "$FP" "$PRIORITY"
-done
+done < <(find "$JAVADIR" -perm /u=x,g=x,o=x -type f -print0)
 
 # Link the default-java file to this folder
-printf '%s\n' "sudo ln -sf -T \"$JAVADIR\" \"$JVM_VERS_DIR/default-java\""
-sudo ln -sf -T "$JAVADIR" "$JVM_VERS_DIR/default-java"
+cmd=(ln -sf -T "$JAVADIR" "$JVM_VERS_DIR/default-java")
+log "sudo ${cmd[*]}"
+sudo "${cmd[@]}"
+unset -v cmd
