Update source/.local/bin/nvim Update source/.local/bin/rg

diff --git a/source/dot_local/exact_bin/executable_nvim b/source/dot_local/exact_bin/executable_nvim
--- a/source/dot_local/exact_bin/executable_nvim
+++ b/source/dot_local/exact_bin/executable_nvim
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+set -euC -o pipefail
 neovim_path=~/code/repos/neovim
 neovim="$neovim_path/build/bin/nvim"
 if [ -x "$neovim" ]; then
@@ -6,13 +7,19 @@ if [ -x "$neovim" ]; then
   export VIMRUNTIME="$neovim_path/runtime/"
   exec -- "$neovim" "$@"
 fi
+function find_in_path() {
+  local path cmd exclude="${2:-${BASH_SOURCE[0]}}"
+  cmd=${1%/} cmd="${1##*/}" # remove trailing slash -- then get basename
+  while read -r -d: path; do
+    path=${path:-$PWD}                         # empty path means pwd
+    [ "$path/$cmd" != "$exclude" ] || continue # skip this_file
+    [ -x "$path/$cmd" ] || continue
+    printf '%s' "$path/$cmd" || true
+    return 0
+  done < <(printf '%s' "$PATH:")
+  printf '%s\n' "$cmd: command not found" >&2 || true
+  return 127
+}
 
-while read -r -d: path; do
-  path=${path:-$PWD}                                  # empty path means pwd
-  [ "$path/nvim" != "${BASH_SOURCE[0]}" ] || continue # skip this_file
-  [ -x "$path/nvim" ] || continue
-  exec -- "$path/nvim" "$@" || continue
-done < <(printf '%s' "$PATH:")
-
-printf '%s\n' "nvim: command not found" >&2
-exit 127
+nvim="$(find_in_path nvim)" || exit
+exec -- "$nvim" "$@" || exit
diff --git a/source/dot_local/exact_bin/executable_rg b/source/dot_local/exact_bin/executable_rg
--- a/source/dot_local/exact_bin/executable_rg
+++ b/source/dot_local/exact_bin/executable_rg
@@ -1,41 +1,22 @@
 #!/usr/bin/env bash
-set -euC -o pipefail
 # Sets up rg function for paging rg output, if rg and delta are both available
+set -euC -o pipefail
 function has_cmd() { command -v -- "$@" &>/dev/null; }
-function err() { printf '%s\n' "$@" >&2; }
-function abort() {
-  err "$1"
-  exit "${2:-1}"
+
+function find_in_path() {
+  local path cmd exclude="${2:-${BASH_SOURCE[0]}}"
+  cmd=${1%/} cmd="${1##*/}" # remove trailing slash -- then get basename
+  while read -r -d: path; do
+    path=${path:-$PWD}                         # empty path means pwd
+    [ "$path/$cmd" != "$exclude" ] || continue # skip this_file
+    [ -x "$path/$cmd" ] || continue
+    printf '%s' "$path/$cmd" || true
+    return 0
+  done < <(printf '%s' "$PATH:")
+  printf '%s\n' "$cmd: command not found" >&2 || true
+  return 127
 }
 
-function find_next_command() {
-  local script_dir=${1%/*}
-  local command_name=${1##*/}
-  local real_command=
-
-  local paths=()
-  readarray -d: -t paths < <(printf '%s' "$PATH") # split PATH in to array
-
-  for d in "${paths[@]}"; do
-    d=${d:-.} # if empty, use current directory
-    d=${d%/}  # remove trailing slash, if present
-    if [ "$d" = "$script_dir" ]; then continue; fi
-    if [ -x "$d/$command_name" ]; then
-      real_command="$d/$command_name"
-      break
-    fi
-  done
-
-  if [ -z "$real_command" ]; then
-    return 1
-  fi
-  printf '%s' "$real_command"
-}
-
-rg=$(find_next_command "$0") || abort "${0##*/}: command not found" 127
-
-if [ -t 1 ] && has_cmd delta; then
-  "$rg" --json "$@" | delta
-else
-  "$rg" "$@"
-fi
+rg=$(find_in_path rg) || exit
+{ [ -t 1 ] && has_cmd delta; } || exec "$rg" "$@" || exit
+"$rg" --json "$@" | exec delta
