Update source/.local/bin/gnome-terminal Add source/.local/bin/xdg-terminal-exec

diff --git a/source/dot_local/exact_bin/executable_gnome-terminal b/source/dot_local/exact_bin/executable_gnome-terminal
--- a/source/dot_local/exact_bin/executable_gnome-terminal
+++ b/source/dot_local/exact_bin/executable_gnome-terminal
@@ -1,14 +1,20 @@
 #!/usr/bin/env bash
 # this is a hack to make desktop files with Terminal=true open in the right application
 set -euC -o pipefail
-terms=(x-terminal-emulator wezterm gnome-terminal xterm)
-
-if [ "${1:-}" != "--" ]; then
-  exec /usr/bin/gnome-terminal "$@"
+terms=(xdg-terminal-exec x-terminal-emulator wezterm gnome-terminal xterm)
+GNOME_TERM=/usr/bin/gnome-terminal
+if [ "${1:-}" != "--" ] && [ -x "$GNOME_TERM" ]; then
+  exec "$GNOME_TERM" "$@"
 else
   for t in "${terms[@]}"; do # Find first installed terminal application in $terms
     if command -v "$t" &>/dev/null; then break; fi
   done
-  # may fail if none installed. This is fine.
-  exec "$t" -e "${@:2}"
+  if [ -z "$t" ]; then
+    echo "Could not find a terminal to run" >&2
+    exit 1
+  fi
+  case "$t" in
+  xdg-terminal-exec) exec "$t" "${@:2}" ;;
+  *) exec "$t" -e "${@:2}" ;;
+  esac
 fi
