Update source/.local/bin/start-gdm Update source/.local/bin/stop-gdm
Former-commit-id: f7065ec35f3d374e0dfb5b598a5928180d7d03bc
Former-commit-id: e6f060b69e449f1da1d23485554d1b1072458d91
Former-commit-id: 88b9ee9166069e55efcc6804733c70fe12c20365

diff --git a/source/dot_local/exact_bin/executable_start-gdm b/source/dot_local/exact_bin/executable_start-gdm
--- a/source/dot_local/exact_bin/executable_start-gdm
+++ b/source/dot_local/exact_bin/executable_start-gdm
@@ -12,20 +12,19 @@ Sets systemd to hide its status, shows plymouth on shutdown, and starts gdm thro
 No options or arguments are accepted except --help
 EOF
 }
+log() { printf '%s\n' "$@"; }
+err() { printf "$THIS: %s\n" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
 
 # Basic arg handling
 invalid=false
 for arg; do
   case "$arg" in
   --help | -help | -h) usage && exit 0 ;;
-  -*) abort "unrecognized option '$arg'" && invalid=true ;;
+  -*) err "unrecognized option '$arg'" && invalid=true ;;
   esac
 done
 if [ "$invalid" = true ]; then exit 2; fi
-
-log() { printf '%s\n' "$@"; }
-err() { printf "$THIS: %s\n" "$@" >&2; }
-abort() { err "$1" && exit "${2:-1}"; }
 
 remove_from_file() {
   local file=$1
diff --git a/source/dot_local/exact_bin/executable_stop-gdm b/source/dot_local/exact_bin/executable_stop-gdm
--- a/source/dot_local/exact_bin/executable_stop-gdm
+++ b/source/dot_local/exact_bin/executable_stop-gdm
@@ -11,17 +11,19 @@ Sets systemd to show its status, hides plymouth on shutdown, and stops gdm throu
 No options or arguments are accepted except --help
 EOF
 }
-
-for arg; do
-  case "$arg" in
-  --help | -help | -h) usage && exit 0 ;;
-  esac
-done
-
-set -eu
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
+
+# Basic arg handling
+invalid=false
+for arg; do
+  case "$arg" in
+  --help | -help | -h) usage && exit 0 ;;
+  -*) err "unrecognized option '$arg'" && invalid=true ;;
+  esac
+done
+if [ "$invalid" = true ]; then exit 2; fi
 
 remove_from_file() {
   local file=$1
