Update source/.local/bin/executables
Former-commit-id: cdf843f170aab2e772fc2485e4a8cb4c0a7e720a
Former-commit-id: 15d85dda541152cf84a5b3dec3c7c21553b4f118
Former-commit-id: 1e7359da544a5aaba2bd8aafe884b5097822cbce

diff --git a/source/dot_local/exact_bin/executable_executables b/source/dot_local/exact_bin/executable_executables
--- a/source/dot_local/exact_bin/executable_executables
+++ b/source/dot_local/exact_bin/executable_executables
@@ -20,40 +20,42 @@ abort() {
   err "$1"
   exit "${2:-1}"
 }
-# Sets the variable $args to an array of positional arguments
-# Usage: parse_args "$@"
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
 function parse_args() {
-  # If awaiting an argument
-  next='' next_arg='' end=false args=()
-  for arg in "$@"; do
-    if [ $end = true ]; then
-      args+=("$arg") && continue
-    elif [ -n "$next" ]; then
-      declare -g "$next"="$arg"
-      next=""
-    else
-      case "$arg" in
-      --help | -h) usage && exit 0 ;;
-      --) end=true ;;
-      -p | --path) next=path next_arg="$arg" ;;
-      --path=*) path="${arg#--path=}" ;;
-      --*) abort "Invalid option -- ${arg#--}" 2 ;;
-      -*) abort "Invalid option -- ${arg#-}" 2 ;;
-      *) args+=("$arg") ;;
-      esac
-    fi
-  done
-  # If awaiting an argument, but end of args
-  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
-  unset end next next_arg
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
 }
 
 path=$PATH
-parse_args "$@"
+LONGOPTS=help,path: SHORTOPTS=h,p
+eval "$(parse_args "$@")"
+
+while true; do
+  case "$1" in
+  --help | -h) usage && exit 0 ;;
+  -p | --path) path="$2" && shift 2 ;;
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
+  esac
+done
 
 get_execs() {
   local d f path dirs=()
-  path="$1"
+  path="${1:-$PATH}"
   if ! [[ $path = *: ]]; then path="$path:"; fi
   readarray -d ':' -t dirs <<<"$path"
   for d in "${dirs[@]}"; do
