Update source/.local/bin/executables Update source/.local/bin/file-count Update source/.local/bin/find-app Update source/.local/bin/fullscreen Update source/.local/bin/gnome-terminal Update source/.local/bin/internet Update source/.local/bin/isotope.dark

diff --git a/source/dot_local/exact_bin/executable_find-app b/source/dot_local/exact_bin/executable_find-app
--- a/source/dot_local/exact_bin/executable_find-app
+++ b/source/dot_local/exact_bin/executable_find-app
@@ -7,35 +7,18 @@
 #
 set -euC -o pipefail
 shopt -s nullglob dotglob globstar
-THIS=contents
+. script_utils.sh || exit
 function usage() {
-  cat <<EOF
-$THIS PATTERN...
+  cat <<EOF || true
+Usage: $THIS PATTERN...
                   
 Finds the path of a .desktop file based on the grep pattern (Searches the Exec=line)
 If passed a program, it will automatically check the executable path
-options:
--h, --help          Shows this help message
--n, --limit         The maximum number of matches to return.
+Options:
+  -h, --help          Shows this help message
+  -n, --limit         The maximum number of matches to return.
 EOF
   return 0
-}
-function log() { printf '%s\n' "$@" || true; }
-function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
-function abort() { err "$1" && exit "${2:-1}"; }
-function has() { [ -x "$(command -v -- "$1")" ]; }
-
-# Returns a string that should be 'eval'ed to set the positional arguments
-# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
-# Input: $LONGOPTS,$SHORTOPTS
-# eval "$(parse_args "$@")"
-function parse_args() {
-  local parsed
-  local code=0 && getopt --test &>/dev/null || code=$?
-  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
-  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
-    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
-  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
 }
 
 limit=''
@@ -49,10 +32,7 @@ while true; do
   *) abort "This is a bug (arg: $1)" 3 ;;
   esac
 done
-
-if [ "$#" -eq 0 ]; then
-  abort 'an application is required' 2
-fi
+[ "$#" -gt 0 ] || abort 'an application is required' 2
 
 readarray -d: -t data_dirs < <(printf '%s' "${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}") # split $XDG_DATA_DIRS in to array
 data_dirs=("${XDG_DATA_HOME:-~/.local/share/}" "${data_dirs[@]}")
@@ -61,9 +41,9 @@ data_dirs=("${XDG_DATA_HOME:-~/.local/share/}" "${data_dirs[@]}")
 function path_is_abs() { [ "${file:0:1}" = '/' ] && [ "${file:0:2}" = "./" ]; }
 
 function find_file() {
-  local exec="$1" dir
+  local exec="$1" dir exec_abs
   [ -n "$exec" ] || return 1 # can't find an empty string!
-  local exec_abs=$(command -v -- "$exec")
+  exec_abs=$(cmdpath "$exec") || true
   local grep_args=(
     --color=auto -r -m1
     -e "^Exec=$exec\b"
