Update source/.local/bin/brightness Add source/.local/bin/cpumode Update source/.local/bin/logind-run Update source/.local/bin/script_utils.sh Update source/.local/bin/sort-files Update source/.local/bin/start-gdm Update source/.local/bin/stop-gdm Update source/.local/bin/update Update source/.local/bin/update-java
Former-commit-id: b30d82ec16f75a22d4251a3223384f1086b2892c
Former-commit-id: 7836443698c5ba2f599e94f5717fa01ddca72578
Former-commit-id: 78b698bd42567ef963145176f894d7d0b56fac88

diff --git a/source/dot_local/exact_bin/executable_start-gdm b/source/dot_local/exact_bin/executable_start-gdm
--- a/source/dot_local/exact_bin/executable_start-gdm
+++ b/source/dot_local/exact_bin/executable_start-gdm
@@ -15,6 +15,11 @@ EOF
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
+# use like '$sudo do_something' - could break with SUDO="something with spaces"
+sudo=
+if [ "$(id -u)" -ne 0 ]; then
+  sudo="${SUDO:-sudo}"
+fi
 
 # Basic arg handling
 invalid=false
@@ -40,15 +45,15 @@ concat() { printf '%s ' "$@"; }
 tmp_file="$(mktemp)" || abort "Error making tmp file"
 trap 'rm -f "$tmp_file"' EXIT
 
-sudo kill -s SIGRTMIN+21 1 || abort "Error setting systemd to hide status"
+$sudo kill -s SIGRTMIN+21 1 || abort "Error setting systemd to hide status"
 # reads from mount if present
 concat "$(remove_from_file /proc/cmdline 'splash' 'nosplash' 'plymouth.enable=0')" "splash" >|"$tmp_file"
 # This fails if not a mount
-sudo umount /proc/cmdline -q || true
-sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Failed to make bind mount on /proc/cmdline'
+$sudo umount /proc/cmdline -q || true
+$sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Failed to make bind mount on /proc/cmdline'
 
 # Cleanup
 rm -f "$tmp_file" && trap '' EXIT
 
 # start the graphical system
-exec sudo systemctl isolate graphical.target
+exec $sudo systemctl isolate graphical.target
diff --git a/source/dot_local/exact_bin/executable_stop-gdm b/source/dot_local/exact_bin/executable_stop-gdm
--- a/source/dot_local/exact_bin/executable_stop-gdm
+++ b/source/dot_local/exact_bin/executable_stop-gdm
@@ -14,6 +14,11 @@ EOF
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
+# use like '$sudo do_something'
+sudo=
+if [ "$(id -u)" -ne 0 ]; then
+  sudo="${SUDO:-sudo}"
+fi
 
 # Basic arg handling
 invalid=false
@@ -38,14 +43,14 @@ concat() { printf '%s ' "$@"; }
 
 tmp_file="$(mktemp)" || return 1
 trap 'rm -f "$tmp_file"' EXIT
-sudo kill -s SIGRTMIN+20 1 || abort "Error setting systemd to output messages"
+$sudo kill -s SIGRTMIN+20 1 || abort "Error setting systemd to output messages"
 # make plymouth hidden
 concat "$(remove_from_file /proc/cmdline 'splash')" 'nosplash' >|"$tmp_file"
 
-sudo umount /proc/cmdline -q || true
-sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Error mounting /proc/cmdline'
+$sudo umount /proc/cmdline -q || true
+$sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Error mounting /proc/cmdline'
 
 # cleanup
 rm -f "$tmp_file" && trap '' EXIT
 
-exec sudo systemctl isolate multi-user.target
+exec $sudo systemctl isolate multi-user.target
