Update source/.local/bin/brightness
Former-commit-id: 4e717908a0650c614539c6bff1d1540011a41864
Former-commit-id: 719ddc44e4ef2b1529580c471ad3322ff7378c98
Former-commit-id: cc5b487870d12bc8fb40ee0d26da5aced1b1b59e

diff --git a/source/dot_local/exact_bin/executable_brightness b/source/dot_local/exact_bin/executable_brightness
--- a/source/dot_local/exact_bin/executable_brightness
+++ b/source/dot_local/exact_bin/executable_brightness
@@ -22,20 +22,39 @@ log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
 
-show=false end=false args=()
-for arg; do
-  # stop processing when hit --
-  if [ "$end" = true ]; then args+=("$arg") && continue; fi
-  case "$arg" in
-  -h | --help) usage && exit 0 ;;
-  show | --show) show=true ;;                     # Verbose option
-  --) end=true ;;                                 # End of args. this is not one.
-  --*) abort "invalid option -- '${arg#--}'" 2 ;; # Invalid -flag
-  -*) abort "invalid option -- '${arg#-}'" 2 ;;   # Invalid -flag
-  *) args+=("$arg") ;;                            # Any other argument
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+
+show=false
+LONGOPTS=help,show SHORTOPTS=h,s
+eval "$(parse_args "$@")"
+
+while true; do
+  case "$1" in
+  --help | -h) usage && exit 0 ;;
+  -s | --show) show=true && shift ;;
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
   esac
 done
-unset end arg
+if [ "${1:-}" = show ]; then show=true; fi
 
 BrPath=$(find /sys/class/backlight -maxdepth 1 -mindepth 1 -print0 | head -zn1)
 BrMax=$(cat "$BrPath/max_brightness")
