Update source/.local/bin/logind-run Update source/.local/bin/script_utils.sh

diff --git a/source/dot_local/exact_bin/executable_logind-run b/source/dot_local/exact_bin/executable_logind-run
--- a/source/dot_local/exact_bin/executable_logind-run
+++ b/source/dot_local/exact_bin/executable_logind-run
@@ -1,42 +1,17 @@
 #!/usr/bin/env bash
-#
-# This file echoes a bunch of color codes to the
-# terminal to demonstrate what's available.  Each
-# line is the color code of one forground color,
-# out of 17 (default + 16 escapes), followed by a
-# test use of that color on all nine background
-# colors (default + 8 escapes).
-#
 set -euC -o pipefail
+. script_utils.sh || exit
 
 ## UTILS ##################################
-THIS='logind-run'
 function usage() {
-
-  cat <<EOF
-$THIS [-h] TTY -- COMMAND [ARGUMENTS]...
+  cat <<EOF || true
+Usage: $THIS [-h] TTY -- COMMAND [ARGUMENTS]...
 Runs a COMMAND on TTY with a new logind session
-
-the environment variable \`SUDO\` can be set to use a different
-program for root elevation. It will be split by the shell, so
-spaces in the program name will likely be mutilited.
 
 OPTIONS:
   -h, --help      display this help message
 EOF
-  return 0
 }
-function log() { printf '%s\n' "$@"; }
-function err() { printf "$THIS: %s\n" "$@" >&2; }
-function abort() {
-  err "$1"
-  exit "${2:-1}"
-}
-# use like `"${sudo[@]}" do_something`
-# shellcheck disable=SC2206 # Splitting is intentional.
-sudo=(${SUDO:-sudo})
-[ "$(id -u)" -eq 0 ] && sudo=()
-
 for arg; do
   case "$arg" in
   --help | -h) usage && exit 0 ;;
@@ -44,32 +19,21 @@ for arg; do
   esac
 done
 
-if [ "$#" -lt 1 ]; then
-  abort 'tty must be specified' 2
-elif [ -z "${2:-}" ]; then
-  abort 'command must be specified' 2
-fi
+[ "$#" -gt 0 ] || abort 'tty must be specified' 2
+[ -n "${2:-}" ] || abort 'command must be specified' 2
 
 ttynum=${1:-34}
-# permit /dev/tty2 to work
-case "$ttynum" in
-/dev/tty*) ttynum=${ttynum#/dev/tty} ;;
-esac
+ttynum=${ttynum#/dev/tty} allow /dev/tty2 to work
 
 re='^[0-9]+$'
-if [ -z "$ttynum" ]; then
-  abort "tty can't be empty" 2
-elif ! [[ "$ttynum" =~ $re ]]; then
-  abort 'tty must be a number' 2
-elif ! [ -c "/dev/tty$ttynum" ]; then # Character special file
-  abort "tty must be a file in /dev/tty*" 2
-fi
-
+[ -n "$ttynum" ] || abort "tty can't be empty" 2
+[[ "$ttynum" =~ $re ]] || abort 'tty must be a number' 2
+[ -c "/dev/tty$ttynum" ] || abort "tty must be a file in /dev/tty*" 2
 if pgrep 'tty' -t "tty$ttynum" &>/dev/null; then
   abort "It seems like this tty is in use. Please try a different tty" 1
 fi
 
-exec "${sudo[@]}" env "PATH=$PATH" systemd-run \
+set_sudo_cmd && exec "${sudo[@]}" env "PATH=$PATH" systemd-run \
   --property PAMName=login \
   --property User="$USER" \
   --property StandardInput=tty \
