Update source/.local/bin/new

diff --git a/source/dot_local/exact_bin/executable_new b/source/dot_local/exact_bin/executable_new
--- a/source/dot_local/exact_bin/executable_new
+++ b/source/dot_local/exact_bin/executable_new
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 # don't match -> empty string. Include dotfiles. Allow double star
-shopt -s nullglob dotglob extglob
+shopt -s nullglob dotglob globstar
 set -euC -o pipefail
 
 template_parent_dir="$HOME/code"
@@ -10,12 +10,29 @@ usage() {
 Usage: $THIS [LANG] [--] <DIR>...
 Creates a new project in the given language, based on the template found at $template_parent_dir/LANG/template
 
+First checks for new-LANG command, if found, pass DIRs and exit
+Second checks for a file $template_parent_dir/LANG/template, if found, pass DIRs and exit
+Third checks for a directory $template_parent_dir/LANG/template, if found, copy to DIRs and continue
+
+
+For each DIR, a series of variable expansions are applied to the filenames and contents of all files and directories contained
+Variables (List may be incomplete):
+    FILEPATH:		The filepath relative to root -- root/dir/file.ext -> dir/file.ext
+    REALPATH:		The full realpath             -- root/dir/file.ext -> /home/aaron/root/dir/file.ext
+    FILENAME:		The basename of file          -- root/dir/file.ext -> file.ext
+    DIRNAME:		The name of parent directory  -- root/dir/file.ext -> root/dir
+    EXTENSION:	The file extension (last!)    -- root/dir/file.ext -> .ext
+    BASENAME:		The name without extension    -- root/dir/file.ext -> file
+    ROOT:				The name of root (project)    -- root/dir/file -> root
+
 OPTIONS:
-  -h, --help     display this help message
-  -l, --lang     the language of the project
+  -l, --lang LANG     the language of the project (language argument is treated as DIR)
+  -h, --help          display this help message
+  -d, --debug         enable debugging output
 EOF
   return 0
 }
+function debug() { if [ -n "${DEBUG:-}" ]; then printf 'DEBUG: %s\n' "$@" >&2 || true; fi; }
 function err() { printf '%s\n' "$@" >&2 || true; }
 function log() { printf '%s\n' "$@" || true; }
 function abort() {
@@ -61,6 +78,38 @@ function substitute() {
 
   perl -pe 's;(\\*)(\$'"$env_pattern"'|\$\{'"$env_pattern"'\});substr($1,0,int(length($1)/2)).(length($1)%2?$2:$ENV{$3||$4});eg' # Source: https://stackoverflow.com/a/25019138
 }
+# usage: for f in "$dest"/*; do handle_file_sub "$f"; done
+# Handles substitutions in filenames and contents recursively
+# This must be recursively to handle a changing file tree.
+# Uses environment variable $tmp as a temporary file
+function handle_file_sub() {
+  local f="$1" filename dir newname
+  debug "handling $f"
+  # handle filename replacements
+  filename=$(basename -- "$f") dir=$(dirname -- "$f")
+  newname=$(substitute "$f" <<<"$filename") # Note: FILEPATH,REALPATH,FILENAME,EXTENSION,BASENAME are relatively useless here
+  case "$newname" in
+  "$filename") ;; # ignore if same
+  */../* | ../* | */..) err "Disallowed directory traversal: $newname. Skipping." ;;
+  */*) mkdir -p "$dir/$(dirname -- "$newname")" ;& # make the directory and fallthrough
+  *)
+    debug "move to $dir/$newname"
+    mv "$f" "$dir/$newname" # move to new location
+    f="$dir/$newname"       # ensure future references are correct
+    ;;
+  esac
+
+  # handle string replacements
+  if [ -d "$f" ]; then
+    for d in "$f"/*; do handle_file_sub "$d"; done
+  elif ! [ -L "$f" ] && [ -f "$f" ]; then # Don't write to links
+    debug "handle file $f"
+    # shellcheck disable=SC2094 # substitute doesn't output to a file
+    substitute "$f" <"$f" >|"$tmp"                             # Write to tmp file to avoid loosing data (https://www.shellcheck.net/wiki/SC2094)
+    cp -p --attributes-only -- "$f" "$tmp" 2>/dev/null || true # save the attributes from the original file (if possible)
+    mv -f -- "$tmp" "$f"                                       # overwrite existing file
+  fi
+}
 
 # Returns a string that should be 'eval'ed to set the positional arguments
 # Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
@@ -75,13 +124,14 @@ function parse_args() {
   printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
 }
 
-LONGOPTS=help,lang: SHORTOPTS=h,l:
+LONGOPTS=help,lang:,debug SHORTOPTS=h,l:,d
 ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING"
 lang=
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
   --lang | -l) lang="$2" && shift 2 ;;
+  --debug | -d) DEBUG=1 && shift 1 ;;
   --) shift && break ;;
   *) abort "This is a bug" 3 ;;
   esac
@@ -100,17 +150,23 @@ if [ -z "$lang" ]; then
     ;;
   esac
 fi
-
 [ -z "$lang" ] && abort "language is required" 2
+if [ "$#" -eq 0 ]; then set -- new; fi # default to 'new' if no arguments given
+
 cmd=$(cmdpath "new-$lang")
 if [ -x "$cmd" ]; then exec -- "$cmd" "$@"; fi # new-$lang command
 
 template_dir="$template_parent_dir/$lang/template" # find the template directory
 # Doesn't exist. Warn the user!
-if ! [ -d "$template_dir" ]; then abort "Could not find $template_dir. Aborting!" 2; fi
-log "Using template '$template_dir'"
+if [ -f "$template_dir" ]; then
+  log "Using '$template_dir' as the template file"
+  [ -x "$template_dir" ] || abort "$template_dir is not executable! Aborting!" 1
+  exec -- "$template_dir" "$@"
+elif ! [ -d "$template_dir" ]; then
+  abort "Could not find $template_dir. Aborting!" 1
+fi
+log "Using template directory '$template_dir'"
 
-if [ "$#" -eq 0 ]; then set -- new; fi # default to 'new' if no arguments given
 # use one file for all loops -- but we don't need it if there's no template
 tmp="$(mktemp)" && trap _cleanup EXIT
 for dest in "$@"; do
@@ -125,25 +181,7 @@ for dest in "$@"; do
   # shellcheck disable=SC2034 # These are dynamically used later
   DATE=$(date '+%m/%d/%Y') TIME=$(date '+%H:%M')
 
-  # Note: FILEPATH,REALPATH,FILENAME,EXTENSION,BASENAME are relatively useless here
-  for f in "$dest"/**; do # handle filename replacements
-    filename=$(basename -- "$f") dir=$(dirname -- "$f")
-    newname=$(substitute "$f" <<<"$filename")
-    case "$newname" in
-    "$filename") ;; # ignore if same
-    */../* | ../* | */..) err "Disallowed directory traversal: $newname. Skipping." ;;
-    */*) mkdir -p "$dir/$(dirname -- "$newname")" ;& # make the directory and fallthrough
-    *) mv "$f" "$dir/$newname" ;;                    # move to new location
-    esac
-  done
-
-  for f in "$dest"/**; do               # handle string replacements
-    if ! [ -f "$f" ]; then continue; fi # ignore directories
-    # shellcheck disable=SC2094 # substitute doesn't output to a file
-    substitute "$f" <"$f" >|"$tmp"                             # Write to tmp file to avoid loosing data (https://www.shellcheck.net/wiki/SC2094)
-    cp -p --attributes-only -- "$f" "$tmp" 2>/dev/null || true # save the attributes from the original file (if possible)
-    mv -f -- "$tmp" "$f"                                       # overwrite existing file
-  done
+  for f in "$dest"/*; do handle_file_sub "$f"; done
 done
 
 _cleanup # Explicitly cleanup if this is reached
