Update source/.local/bin/sync-java

diff --git a/source/dot_local/exact_bin/executable_sync-java b/source/dot_local/exact_bin/executable_sync-java
--- a/source/dot_local/exact_bin/executable_sync-java
+++ b/source/dot_local/exact_bin/executable_sync-java
@@ -9,35 +9,43 @@
 set -euC -o pipefail
 shopt -s nullglob globstar # Better globs
 . script_utils.sh || exit
-deps=(rsync diff)
-exclude=('*.class' 'System Volume Information')
+USE_COLOR=1 # Enable color
+deps=(rsync diff) exclude=('*.class' 'System Volume Information')
+default_dest="/media/$USER/AARONDILL" default_src="${java:-$HOME/code/java}"
+
 function usage() {
   cat <<EOF
-$THIS [options] [--] [dest] [src]
+Usage: $THIS [options] [--] [dest] [src]
 Syncs src to dest. Note: this is a destructive operation. Any files in dest will be overwritten or deleted.
 
 Options:
   -e, --exclude=exclude    A colon separated list of file globs to exclude (defualt: $(join ":" "${exclude[@]}"))
   -h, --help               Show this message
   -k, --keep               Keep files present in dest, but not in src. This can be used to later run \`$THIS src dest\`.
+  -d, --diff               Only show the diff between src and dest.
   -y, --yes                Don't ask for confirmation
+
+Defaults: 
+  dest=$default_dest
+  src=$default_src
+
+Dependencies: $(join ', ' "${deps[@]}")
 EOF
   return 0
 }
 
-LONGOPTS=help,yes,keep,exclude: SHORTOPTS=h,y,k,e:
+LONGOPTS=diff,exclude:,help,keep,yes SHORTOPTS=d,e:,h,k,y
 ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
 
-yes=0 keep=0
+yes=0 keep=0 diff_only=0
 while true; do
   case "$1" in
+  -d | --diff) diff_only=1 && shift ;;
   -h | --help) usage && exit 0 ;;
-  -y | --yes) yes=1 && shift ;;
-  -q | --quiet) USE_VERBOSE=0 && shift ;; # make the verbose function not output
   -k | --keep) keep=1 && shift ;;
+  -q | --quiet) USE_VERBOSE=0 && shift ;; # make the verbose function not output
+  -y | --yes) yes=1 && shift ;;
   -e | --exclude)
-    exclude_add=()
-    # note: a here-doc can't be used because it appends a newline
     readarray -d: -t exclude_add < <(printf '%s' "$2") || true
     exclude+=("${exclude_add[@]}")
     ;;
@@ -46,16 +54,21 @@ while true; do
   esac
 done
 
-# Dest defaults to my personal USB's name
-dest="${1:-/media/$USER/AARONDILL}"
-src="${2:-${java:-$HOME/code/java}}"
+dest="${1:-$default_dest}"
+src="${2:-$default_src}"
 
 [ -d "$dest" ] || abort "dest: $dest is not a directory!" 1
 [ -d "$src" ] || abort "src: $src is not a directory!" 1
 
+if [ "$diff_only" -eq 1 ]; then
+  check_dependencies diff || exit
+  verbose diff -r -- "$dest" "$src"
+  exit 0 # Stop here. they don't want to sync.
+fi
+
 check_dependencies "${deps[@]}" || exit
 # note: diff dest src to show what copying *will do*
-[ "$yes" -eq 1 ] || verbose diff -r -- "$dest" "$src" || confirm "source and destination differ. Do you want to override destination?" y || abort 'aborting' 1
+[ "$yes" -eq 1 ] || verbose diff -r -- "$dest" "$src" || confirm "source and destination differ. Do you want to override destination?" || abort 'aborting' 1
 # verbose, archive, recursive, update, progress
 rsync_args=(-varuP)
 [ "$keep" -eq 1 ] || rsync+=(--delete) # if not keep, then delete files not present in src
