Update source/.local/bin/internet
Former-commit-id: 3d8e00ff9b930cdbe574676e54792c4af392a043
Former-commit-id: 151fe89dfa192371a892f70f15ca0213df52f892
Former-commit-id: 765ad2a5d699af1686ba644c417592fa466f0875

diff --git a/source/dot_local/exact_bin/executable_internet b/source/dot_local/exact_bin/executable_internet
--- a/source/dot_local/exact_bin/executable_internet
+++ b/source/dot_local/exact_bin/executable_internet
@@ -26,38 +26,42 @@ log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
 
-# Sets the variable $args to an array of positional arguments
-# Usage: parse_args "$@"
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
 function parse_args() {
-  # If awaiting an argument
-  next='' next_arg='' end=false args=()
-  for arg in "$@"; do
-    if [ $end = true ]; then
-      args+=("$arg") && continue
-    elif [ -n "$next" ]; then
-      # Declare -x to expose outside the function
-      declare -g "$next"="$arg"
-      next=""
-    else
-      case "$arg" in
-      --help | -h) usage && exit 0 ;;
-      --) end=true ;;
-      -q | --quiet) quiet=true ;;
-      -t | --test) next=test_url next_arg="$arg" ;;
-      --test=*) test_url="${arg#--test=}" ;;
-      --*) abort "Invalid option -- ${arg#--}" 2 ;;
-      -*) abort "Invalid option -- ${arg#-}" 2 ;;
-      *) args+=("$arg") ;;
-      esac
-    fi
-  done
-  # If awaiting an argument, but end of args
-  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
-  unset end next next_arg
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
 }
 
+# option --long/-l requires 1 argument
+LONGOPTS=short,long:,help
+SHORTOPTS=h,s,l:
+ARGSTRING="$(parse_args "$@")"
+eval "$ARGSTRING"
 quiet=false
-parse_args "$@"
+while true; do
+  case "$1" in
+  --help | -h) usage && exit 0 ;;
+  --) shift && break ;;
+  -q | --quiet) quiet=true && shift ;;
+  -t | --test) test_url=$2 && shift 2 ;;
+  *) abort "This is a bug" 3 ;;
+  esac
+done
 
 exit=0
 if [ $quiet = true ]; then
