Update source/.local/bin/visual
Former-commit-id: 18ba54e288074c813b5c09830455e647c4a67857
Former-commit-id: ce1eb72d5f423c19bf2cc9f564f49cf9657d150d
Former-commit-id: af35927def88ea9262d5a6eb9fe9afe33a40f675

diff --git a/source/dot_local/exact_bin/executable_visual b/source/dot_local/exact_bin/executable_visual
--- a/source/dot_local/exact_bin/executable_visual
+++ b/source/dot_local/exact_bin/executable_visual
@@ -20,11 +20,16 @@ EOF
 log() { printf '%s\n' "$@"; }
 err() { printf "${THIS:-}: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
+cmd() { command -v "$@" &>/dev/null; }
+
+if ! cmd which; then abort "which is required for this script" 1; fi
+if ! cmd startx; then abort "startx is required for this script" 1; fi
 
 inhibit=0
 if [ "${1:-}" = "--supress-power" ]; then
   inhibit=1
   shift
+  if ! cmd systemd-inhibit; then err "systemd-inhibit is required to inhibit the power key" && inhibit=0; fi
 fi
 
 for arg in "$@"; do
