Update source/.local/bin/cleanup Update source/.local/bin/downloaded Update source/.local/bin/script_utils.sh Update source/.local/bin/snap-cleanup

diff --git a/source/dot_local/exact_bin/executable_cleanup b/source/dot_local/exact_bin/executable_cleanup
--- a/source/dot_local/exact_bin/executable_cleanup
+++ b/source/dot_local/exact_bin/executable_cleanup
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 set -euC -o pipefail
 shopt -s nullglob globstar # Better globs
+USE_COLOR=1                # We want color in logs here
+
 # Find the current file and it's directory # Source: https://stackoverflow.com/a/246128
 SOURCE="${BASH_SOURCE[0]:-}" DIR=''
 while [ -L "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
@@ -45,10 +47,10 @@ fi
 # Start doing things
 
 if has_cmd pnpm; then
-  log_c "Cleaning pnpm store"
+  log "Cleaning pnpm store"
   (
     cd # pnpm has issues if the current directory is not writable.
-    verbose_c pnpm store prune || true
+    verbose pnpm store prune || true
   )
 fi
 if has_cmd bun; then
@@ -56,15 +58,15 @@ if has_cmd bun; then
     mkdir -p "$BUN_INSTALL/install/global/"
     touch "$BUN_INSTALL/install/global/package.json"
   fi
-  log_c "Cleaning bun cache"
-  verbose_c bun pm -g cache rm
+  log "Cleaning bun cache"
+  verbose bun pm -g cache rm
 fi
 
-log_c "Cleaning browser cache"
+log "Cleaning browser cache"
 # Cleaner output
-NO_MEASURE_DISK_DIFF=1 verbose_c clean-google-cache || true
+NO_MEASURE_DISK_DIFF=1 verbose clean-google-cache || true
 
-log_c "Cleaning up cache files"
+log "Cleaning up cache files"
 rm -rf -- ~/.cache/node/corepack/ || true
 rmdir --ignore-fail-on-non-empty -- ~/.cache/node/ || true
 rm -rf -- ~/.cache/npm/ || true
@@ -72,28 +74,28 @@ rm -rf -- ~/.cache/yarn/ || true
 rm -rf -- ~/.cache/gnome-desktop-thumbnailer/ || true
 rm -rf -- ~/.cache/mesa_shader_cache/ || true
 
-log_c "Cleaning the trash"
+log "Cleaning the trash"
 if has_cmd trash-empty; then
-  verbose_c trash-empty || true
+  verbose trash-empty || true
 elif has_cmd gio; then
-  verbose_c gio trash --empty || true
+  verbose gio trash --empty || true
 else
-  err_c "Could not find a command to clean the trash"
+  err "Could not find a command to clean the trash"
 fi
 
 has_root=1
 if [ "$(id -u)" -ne 0 ]; then
-  log_c "Note: the following commands require root access. Running sudo to cache password."
-  log_c "(If you do not have root access, exit the prompt and these actions will be skipped.)"
+  log "Note: the following commands require root access. Running sudo to cache password."
+  log "(If you do not have root access, exit the prompt and these actions will be skipped.)"
   sudo_cmd true || has_root=0
 fi
 
 if [ "$has_root" -eq 1 ]; then
   if has_cmd snap; then
-    log_c "Cleaning up snap packages"
+    log "Cleaning up snap packages"
     sudo_cmd "$(cmdpath snap-cleanup)" -y || true
   fi
-  log_c "Cleaning package manager cache"
+  log "Cleaning package manager cache"
   if has_cmd nala; then
     sudo_cmd nala clean || true
   elif has_cmd apt; then
@@ -103,19 +105,19 @@ if [ "$has_root" -eq 1 ]; then
   elif has_cmd pacman; then
     sudo_cmd pacman -Sc || true
   else
-    err_c "Could not find a package manager to clean up"
+    err "Could not find a package manager to clean up"
   fi
 
   if has_cmd flatpak; then
-    log_c "Repairing flatpak repo"
+    log "Repairing flatpak repo"
     sudo_cmd flatpak repair || true
   fi
 
-  log_c "Cleaning old logs >1G"
+  log "Cleaning old logs >1G"
   sudo_cmd journalctl --vacuum-size=1G || true
 
   # This should be done last. It will (likely) not free any space, but should still be regularly done
-  log_c "Running TRIM on mounted partitions"
+  log "Running TRIM on mounted partitions"
   sudo_cmd fstrim -av || true # this may fail (ex: in container or unsupported fs)
 fi
 
@@ -128,6 +130,6 @@ if [ "$(get_fs_root /)" != "$(get_fs_root ~)" ]; then
 fi
 saving=$((oldsize - newsize))
 
-log_c "Old size: $(human_readable "$oldsize")"
-log_c "New size: $(human_readable "$newsize")"
-log_c "Total saving: $(human_readable "$saving")"
+log "Old size: $(human_readable "$oldsize")"
+log "New size: $(human_readable "$newsize")"
+log "Total saving: $(human_readable "$saving")"
