Update source/.local/bin/post-temp Update source/.bashrc.d/40_fzf

diff --git a/source/dot_local/exact_bin/executable_post-temp b/source/dot_local/exact_bin/executable_post-temp
--- a/source/dot_local/exact_bin/executable_post-temp
+++ b/source/dot_local/exact_bin/executable_post-temp
@@ -11,25 +11,27 @@ if [ -f "$dir/$utils" ]; then utils="$dir/$utils"; fi
 # shellcheck source=./script_utils.sh
 . "$utils"
 
-temp_source=https://tmpfiles.org/api/v1/upload
+# default_temp_source=https://tmpfiles.org/api/v1/upload
+default_temp_source=https://file.io
 
 function usage() {
   cat <<EOF || true
 Usage: $THIS [OPTION...] [--] FILE...
 Hosts a temporary file on the internet for 60 mins and outputs the url.
+Note: requires jq to output the url. If jq is not installed (or -t is specified)
+the full server response will be output.
 
 OPTIONS:
   -h, --help         display this help message
   -v, --verbose      display verbose messages
   -q, --quiet        be quieter
-  -t, --temp=url     use url to upload files (POST) (default: $temp_source)
-  -p, --python=path  use path as python interpreter to parse json instead of searching PATH.
+  -t, --temp=url     use url to upload files (POST) (default: $default_temp_source)
 EOF
 }
-LONGOPTS=help,verbose,quiet,python:,temp: SHORTOPTS=h,v,q,p:,t:
+LONGOPTS=help,verbose,quiet,temp: SHORTOPTS=h,v,q,t:
 ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
 
-verbose=0 quiet=0 python=
+verbose=0 quiet=0 temp_source="$default_temp_source"
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
@@ -37,14 +39,13 @@ while true; do
   -v | --verbose) verbose=1 && shift ;; # Verbose option
   -q | --quiet) quiet=1 && shift ;;     # Quiet option
   -t | --temp) temp_source="$2" && shift 2 ;;
-  -p | --python) python="$2" && shift 2 ;;
   *) abort "This is a bug" 3 ;;
   esac
 done
 
 [ "$#" -gt 0 ] || abort "FILE is required!" 2 # Error if no files given
 
-[ -n "$python" ] || python=$(cmdpath python3 || cmdpath python) || true
+jq=$(cmdpath jq) || true
 
 declare -i exitcode=0
 for file in "$@"; do
@@ -55,23 +56,28 @@ for file in "$@"; do
   # {"message": "server error"}
   # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}
 
-  # If verbose, or python not installed, print entire json
-  if [ "$verbose" = 1 ] || [ -z "$python" ]; then
-    log "$result"
-    [ -n "$python" ] || continue # Stops loop here because python is not installed
+  # If verbose, jq not installed, or unrecognized temp_source, then print entire json
+  if [ "$verbose" = 1 ] || [ -z "$jq" ] || [ "$temp_source" != "$default_temp_source" ]; then
+    # Pretty print if possible, else log it.
+    if [ -n "$jq" ]; then jq <<<"$result"; else log "$result"; fi
+    [ "$verbose" = 1 ] || continue # If any other condition was met, skip the rest of the loop
   fi
 
-  # Print the result thru python to get the data
-  status=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'status' in j and print(j['status'])" <<<"$result")
-  url=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'data' in j and 'url' in j['data'] and print(j['data']['url'])" <<<"$result")
+  # status=$("$jq" -re ".status") || status=''
+  # url=$("$jq" -re ".data.url" <<<"$result") || url=""
+
+  # exits 1 if falsy
+  "$jq" -re ".success" <<<"$result" &>/dev/null && status=success || status=
+  url=$("$jq" -re ".link" <<<"$result") || url=""
 
   if [ -z "$status" ] || [ -z "$url" ]; then
-    message=$(python3 -c "import sys, json; j=json.load(sys.stdin); 'message' in j and print(j['message'])" <<<"$result")
-    if [ -n "$message" ]; then err "$message"; else err "An unknown error occured"; fi
+    message=$("$jq" -re .message <<<"$result") || message=''
+    err "${message:-An unknown error occured}"
     exitcode=1
   else
     [ "$quiet" == 1 ] || err "$status"
-    log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
+    # log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
+    log "$url"
   fi
 done
 
