Update source/.local/bin/snap-cleanup
Former-commit-id: f9cee19e0617b64aba09659585d32f2d61a10323
Former-commit-id: 9ea35df4b62d33d0f3bb4d03951c6b20fa928c69
Former-commit-id: 93f030b1acf0a9687c7401cff57f03651b755207

diff --git a/source/dot_local/exact_bin/executable_snap-cleanup b/source/dot_local/exact_bin/executable_snap-cleanup
--- a/source/dot_local/exact_bin/executable_snap-cleanup
+++ b/source/dot_local/exact_bin/executable_snap-cleanup
@@ -1,9 +1,7 @@
 #!/bin/bash
+set -euC -o pipefail
 
-# Error status variables
-STATUS_OK=0
-STATUS_ERROR=1
-
+THIS=script_utils.sh
 # Color settings
 YELLOW_COLOR="\033[1;33m"
 RED_COLOR="\033[0;31m"
@@ -12,11 +10,57 @@ OFF_COLOR="\033[0m"
 # Set English language
 LANG=en_US.UTF-8
 
+usage() {
+  cat <<EOF
+$THIS [options] [--] [arguments]
+Cleans up the excess snap revisions and files
+
+Options:
+-h, --help        show this message
+EOF
+  return 0
+}
+
+log() { printf '%s\n' "$@"; }
+err() { printf "$RED_COLOR$THIS: %s\n$OFF_COLOR" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
+
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+
+# option --long/-l requires 1 argument
+LONGOPTS=help SHORTOPTS=h
+ARGSTRING="$(parse_args "$@")"
+eval "$ARGSTRING"
+
+while true; do
+  case "$1" in
+  -h | --help) usage && exit 0 ;;
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
+  esac
+done
+
 # Execute it as root user
-if [ "${USER}" != root ]; then
-  echo -e "${RED_COLOR}ERROR: must be root! Exiting...${OFF_COLOR}"
-  exit "${STATUS_ERROR}"
-fi
+if [ "${USER}" != root ]; then abort "Must be root! Aborting..."; fi
 
 # Current status
 USED_BEFORE="$(df -k / | awk 'NR>1 {print $3}')"
@@ -28,19 +72,19 @@ if [ -n "$(command -v snap)" ]; then
   KEY="${KEY:0:1}" && KEY="${KEY,,}"
   if [ "${KEY}" = "y" ] || [ "${KEY}" = "" ]; then
     # remove unused snapd revisions
-    echo "Removing unused snapd revisions..."
+    log "Removing unused snapd revisions..."
     snap set system refresh.retain=2
     # shellcheck disable=SC2162
     snap list --all | awk '/disabled/ {print $1, $3}' |
-    while read SNAP_NAME SNAP_REV; do
-      snap remove "${SNAP_NAME}" --revision="${SNAP_REV}";
-    done
-    if [ -d /var/lib/snapd/cache ] && [ -n "$(ls -A /var/lib/snapd/cache)" ]; then
+      while read SNAP_NAME SNAP_REV; do
+        snap remove "${SNAP_NAME}" --revision="${SNAP_REV}"
+      done
+    if [ -d /var/lib/snapd/cache ] && [ -n "$(find /var/lib/snapd/cache/ -mindepth 1)" ]; then
       rm /var/lib/snapd/cache/*
     fi
-    echo "Nothing unused to uninstall"
+    log "Nothing unused to uninstall"
   else
-    echo "Task skipped"
+    log "Task skipped"
   fi
 fi
 
@@ -48,6 +92,4 @@ fi
 USED_AFTER="$(df -k / | awk 'NR>1 {print $3}')"
 
 # Summary
-echo -e "${YELLOW_COLOR}Freed up space: $(( (USED_BEFORE - USED_AFTER)/1024 )) MB${OFF_COLOR}"
-exit "${STATUS_OK}"
-
+log "${YELLOW_COLOR}Freed up space: $(((USED_BEFORE - USED_AFTER) / 1024)) MB${OFF_COLOR}"
