Update source/.local/bin/brightness Update source/.local/bin/cpumode Update source/.local/bin/logind-run Update source/.local/bin/snap-cleanup Update source/.local/bin/sort-files Update source/.local/bin/start-gdm Update source/.local/bin/stop-gdm Update source/.local/bin/update Update source/.local/bin/update-grub Update source/.local/bin/update-java

diff --git a/source/dot_local/exact_bin/executable_start-gdm b/source/dot_local/exact_bin/executable_start-gdm
--- a/source/dot_local/exact_bin/executable_start-gdm
+++ b/source/dot_local/exact_bin/executable_start-gdm
@@ -10,16 +10,20 @@ usage: $THIS
 
 Sets systemd to hide its status, shows plymouth on shutdown, and starts gdm through systemd graphical.target
 No options or arguments are accepted except --help
+
+the environment variable \`SUDO\` can be set to use a different
+program for root elevation. It will be split by the shell, so
+spaces in the program name will likely be mutilited.
+
 EOF
 }
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
-# use like '$sudo do_something' - could break with SUDO="something with spaces"
-sudo=
-if [ "$(id -u)" -ne 0 ]; then
-  sudo="${SUDO:-sudo}"
-fi
+# use like `"${sudo[@]}" do_something`
+# shellcheck disable=SC2206 # Splitting is intentional.
+sudo=(${SUDO:-sudo})
+[ "$(id -u)" -eq 0 ] && sudo=()
 
 # Basic arg handling
 invalid=false
@@ -45,15 +49,15 @@ concat() { printf '%s ' "$@"; }
 tmp_file="$(mktemp)" || abort "Error making tmp file"
 trap 'rm -f "$tmp_file"' EXIT
 
-$sudo kill -s SIGRTMIN+21 1 || abort "Error setting systemd to hide status"
+"${sudo[@]}" kill -s SIGRTMIN+21 1 || abort "Error setting systemd to hide status"
 # reads from mount if present
 concat "$(remove_from_file /proc/cmdline 'splash' 'nosplash' 'plymouth.enable=0')" "splash" >|"$tmp_file"
 # This fails if not a mount
-$sudo umount /proc/cmdline -q || true
-$sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Failed to make bind mount on /proc/cmdline'
+"${sudo[@]}" umount /proc/cmdline -q || true
+"${sudo[@]}" mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Failed to make bind mount on /proc/cmdline'
 
 # Cleanup
 rm -f "$tmp_file" && trap '' EXIT
 
 # start the graphical system
-exec $sudo systemctl isolate graphical.target
+exec "${sudo[@]}" systemctl isolate graphical.target
diff --git a/source/dot_local/exact_bin/executable_stop-gdm b/source/dot_local/exact_bin/executable_stop-gdm
--- a/source/dot_local/exact_bin/executable_stop-gdm
+++ b/source/dot_local/exact_bin/executable_stop-gdm
@@ -9,16 +9,20 @@ usage: $THIS
 
 Sets systemd to show its status, hides plymouth on shutdown, and stops gdm through systemd multi-user.target
 No options or arguments are accepted except --help
+
+the environment variable \`SUDO\` can be set to use a different
+program for root elevation. It will be split by the shell, so
+spaces in the program name will likely be mutilited.
+
 EOF
 }
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
-# use like '$sudo do_something'
-sudo=
-if [ "$(id -u)" -ne 0 ]; then
-  sudo="${SUDO:-sudo}"
-fi
+# use like `"${sudo[@]}" do_something`
+# shellcheck disable=SC2206 # Splitting is intentional.
+sudo=(${SUDO:-sudo})
+[ "$(id -u)" -eq 0 ] && sudo=()
 
 # Basic arg handling
 invalid=false
@@ -43,14 +47,14 @@ concat() { printf '%s ' "$@"; }
 
 tmp_file="$(mktemp)" || return 1
 trap 'rm -f "$tmp_file"' EXIT
-$sudo kill -s SIGRTMIN+20 1 || abort "Error setting systemd to output messages"
+"${sudo[@]}" kill -s SIGRTMIN+20 1 || abort "Error setting systemd to output messages"
 # make plymouth hidden
 concat "$(remove_from_file /proc/cmdline 'splash')" 'nosplash' >|"$tmp_file"
 
-$sudo umount /proc/cmdline -q || true
-$sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Error mounting /proc/cmdline'
+"${sudo[@]}" umount /proc/cmdline -q || true
+"${sudo[@]}" mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Error mounting /proc/cmdline'
 
 # cleanup
 rm -f "$tmp_file" && trap '' EXIT
 
-exec $sudo systemctl isolate multi-user.target
+exec "${sudo[@]}" systemctl isolate multi-user.target
