Update source/.local/bin/rmgit
Former-commit-id: 8f11e84f9853a1aad7a9571bb9f7113f04933d24
Former-commit-id: c6078e0e3bbaebef3f4d2ea126cbc11ff97acb3d
Former-commit-id: 821fceae7c5c6f80b8df2bdc8be5b7cb2836e541

diff --git a/source/dot_local/exact_bin/executable_rmgit b/source/dot_local/exact_bin/executable_rmgit
--- a/source/dot_local/exact_bin/executable_rmgit
+++ b/source/dot_local/exact_bin/executable_rmgit
@@ -1,12 +1,13 @@
 #!/usr/bin/env bash
+THIS=rmgit
 function log() { printf '%s\n' "$@"; }
-function err() { printf '%s\n' "$@" >&2; }
+function err() { printf "$THIS: %s\n" "$@" >&2; }
 
 declare -i VERBOSE=0 YES=0 FORCE=0
 
 function usage() {
   cat <<-EOF
-	Usage: rmgit [OPTS] REPO...
+	Usage: $THIS [OPTS] REPO...
 
 	Options:
 		-v, --verbose  verbose output
@@ -16,32 +17,37 @@ function usage() {
 EOF
   return 0
 }
-while getopts ':hvyf-:' opt; do
-  case "$opt" in
-  h) usage && exit 0 ;;
-  v) VERBOSE=1 ;;
-  y) YES=1 ;;
-  f) YES=1 FORCE=1 ;;
-  -) case "${OPTARG}" in
-    # Long options
-    help) usage && exit 0 ;;
-    verbose) VERBOSE=1 ;;
-    yes) YES=1 ;;
-    force) YES=1 FORCE=1 ;;
-    *)
-      err "Unknown option --${OPTARG}"
-      usage >&2
-      exit 1
-      ;;
-    esac ;;
-  *)
-    err "Unknown option -${OPTARG}"
-    usage >&2
-    exit 1
-    ;;
-  esac
-done
-shift "$((OPTIND - 1))"
+# Sets the variable $args to an array of positional arguments
+# Usage: parse_args "$@"
+function parse_args() {
+  # If awaiting an argument
+  next='' next_arg='' end=false args=()
+  for arg in "$@"; do
+    if [ $end = true ]; then
+      args+=("$arg") && continue
+    elif [ -n "$next" ]; then
+      # -x to expose outside function
+      declare -g "$next"="$arg"
+      next=""
+    else
+      case "$arg" in
+      --help | -h) usage && exit 0 ;;
+      --) end=true ;;
+      -v | --verbose) VERBOSE=1 ;;
+      -y | --yes) YES=1 ;;
+      -f | --force) FORCE=1 YES=1 ;;
+      --*) abort "Invalid option -- ${arg#--}" 2 ;;
+      -*) abort "Invalid option -- ${arg#-}" 2 ;;
+      *) args+=("$arg") ;;
+      esac
+    fi
+  done
+  # If awaiting an argument, but end of args
+  if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
+  unset end next next_arg
+}
+
+parse_args "$@"
 
 for REPO; do
   if [ -z "$REPO" ]; then
