Update source/.local/bin/start-gdm
Former-commit-id: b5db32b4708fb9bfc1d4c5b963c07e78915dfdc6
Former-commit-id: 8707b09dbbb7bc3605d45ee855d450615a91e043
Former-commit-id: 7d1b3e3c3fda71be1905b13985e0882804b67f10

diff --git a/source/dot_local/exact_bin/executable_start-gdm b/source/dot_local/exact_bin/executable_start-gdm
--- a/source/dot_local/exact_bin/executable_start-gdm
+++ b/source/dot_local/exact_bin/executable_start-gdm
@@ -1,5 +1,6 @@
 #!/usr/bin/env bash
 # This sets systemd to hide it's status, shows plymouth on shutdown, and starts gdm through systemd graphical.target
+set -eu
 
 THIS=start-gdm
 
@@ -12,13 +13,16 @@ No options or arguments are accepted except --help
 EOF
 }
 
+# Basic arg handling
+invalid=false
 for arg; do
   case "$arg" in
   --help | -help | -h) usage && exit 0 ;;
+  -*) abort "unrecognized option '$arg'" && invalid=true ;;
   esac
 done
+if [ "$invalid" = true ]; then exit 2; fi
 
-set -eu
 log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
