Update source/.local/bin/script_utils.sh Update source/.local/bin/sort-files
Former-commit-id: 3747935db196d71d0b9e1ea7ac5cb477b1c9be9d
Former-commit-id: d0ecfa94eecda76a4b8a8b139ecd78b532580f92
Former-commit-id: b3fb7b3dadfb27caee4df79738aed0c9b1f88cf0

diff --git a/source/dot_local/exact_bin/executable_sort-files b/source/dot_local/exact_bin/executable_sort-files
--- a/source/dot_local/exact_bin/executable_sort-files
+++ b/source/dot_local/exact_bin/executable_sort-files
@@ -1,4 +1,52 @@
 #!/usr/bin/env bash
+set -euC -o pipefail
+
+THIS=sort-files
+usage() {
+  cat <<EOF
+$THIS [options] [--] [DIR...]
+Outputs the files in the current (or specified) directory in order of largest to smallest.
+
+Options:
+-h, --help        show this message
+EOF
+  return 0
+}
+
+log() { printf '%s\n' "$@"; }
+err() { printf "$THIS: %s\n" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
+
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
+# Input: $LONGOPTS,$SHORTOPTS,$THIS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+LONGOPTS=help SHORTOPTS=h
+ARGSTRING="$(parse_args "$@")"
+eval "$ARGSTRING"
+while true; do
+  case "$1" in
+  -h | --help) usage && exit 0 ;;
+  *) abort 'This is a bug' 3 ;;
+  esac
+done
+
 sudo du -h --max-depth=1 -a --one-file-system -- "$@" |
   sort -hs |
   # coloring
