Update source/.local/bin/sync-java

diff --git a/source/dot_local/exact_bin/executable_sync-java b/source/dot_local/exact_bin/executable_sync-java
--- a/source/dot_local/exact_bin/executable_sync-java
+++ b/source/dot_local/exact_bin/executable_sync-java
@@ -10,8 +10,30 @@ set -euC -o pipefail
 shopt -s nullglob globstar # Better globs
 . script_utils.sh || exit
 deps=(rsync diff)
+function usage() {
+  cat <<EOF
+$THIS [options] [--] [dest] [src]
+Syncs src to dest. Note: this is a destructive operation. Any files in dest will be overwritten or deleted.
 
-check_dependencies "${deps[@]}"
+Options:
+-h, --help        show this message
+-y, --yes         Don't ask for confirmation
+EOF
+  return 0
+}
+
+LONGOPTS=help,yes SHORTOPTS=h,y
+ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
+yes=0
+while true; do
+  case "$1" in
+  -h | --help) usage && exit 0 ;;
+  -y | --yes) yes=1 && shift ;;
+  -q | --quiet) USE_VERBOSE=0 && shift ;; # make the verbose function not output
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
+  esac
+done
 
 # Dest defaults to my personal USB's name
 dest="${1:-/media/$USER/AARONDILL}"
@@ -20,8 +42,9 @@ src="${2:-${java:-$HOME/code/java}}"
 [ -d "$dest" ] || abort "dest: $dest is not a directory!" 1
 [ -d "$src" ] || abort "src: $src is not a directory!" 1
 
+check_dependencies "${deps[@]}" || exit
 # note: diff dest src to show what copying *will do*
-verbose diff -r -- "$dest" "$src" || confirm "source and destination differ. Do you want to override destination?" || abort 'aborting' 1
+[ "$yes" -eq 1 ] || verbose diff -r -- "$dest" "$src" || confirm "source and destination differ. Do you want to override destination?" || abort 'aborting' 1
 
 exclude=('*.class' 'System Volume Information')
 # verbose, archive, recursive, update, progress, delete
