Update source/.local/bin/brightness
Former-commit-id: 680448569802c164c4751ac6424ef4ddd9d88252
Former-commit-id: 105122eca81a29f2ceca4621c7fdb03c8fce9815
Former-commit-id: 560dbd153a15312d5b45e1f514599f75633a1107

diff --git a/source/dot_local/exact_bin/executable_brightness b/source/dot_local/exact_bin/executable_brightness
--- a/source/dot_local/exact_bin/executable_brightness
+++ b/source/dot_local/exact_bin/executable_brightness
@@ -1,4 +1,41 @@
-#!/bin/sh
+#!/usr/bin/env bash
+
+set -eu
+
+THIS=brightness
+
+usage() {
+  cat <<-EOF
+usage: $THIS [percent]
+       $THIS show
+
+sets the brightness to the specified integer percentage
+What is done depends on the arguments passed:
+  'show':              outputs current brightness percentage.
+  integer percentage:  the brightness will be set to the specified percentage
+  no argument:         a percentage will be retrieved graphically from the user
+
+EOF
+}
+
+log() { printf '%s\n' "$@"; }
+err() { printf "$THIS: %s\n" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
+
+show=false end=false args=()
+for arg; do
+  # stop processing when hit --
+  if [ "$end" = true ]; then args+=("$arg") && continue; fi
+  case "$arg" in
+  -h | --help) usage && exit 0 ;;
+  show) show=true ;;                            # Verbose option
+  --) end=true ;;                               # End of args. this is not one.
+  -*) abort "invalid option -- '${arg#-}'" 2 ;; # Invalid -flag
+  *) args+=("$arg") ;;                          # Any other argument
+  esac
+done
+unset end arg
+
 BrPath=$(find /sys/class/backlight -maxdepth 1 -mindepth 1 | head -n1)
 BrMax=$(cat "$BrPath/max_brightness")
 # 100th max-brightness, rounded up to nearest integer
@@ -7,14 +44,24 @@ BrCur=$(cat "$BrPath/brightness")
 
 BrCurRel=$(printf '%s ' "$BrCur" "$BrMax" | awk '{ print int( $1 / $2 * 100 ) }')
 
+if [ "$show" = true ]; then
+  log "$BrCurRel"
+  exit 0
+fi
+
 # First arg, or menu
-BrNewRel=${1:-}
+BrNewRel=${args[0]:-}
+number_re='^[0-9]+$'
 if [ -z "$BrNewRel" ]; then
   if command -v yad 2>/dev/null >/dev/null; then
     BrNewRel=$(yad --scale --min-value 0 --max-value 100 --value "$BrCurRel" --print-partial --title 'Set brightness' --width 300 --fixed --sticky --mouse --on-top --escape-ok --button OK --hide-value)
   elif command -v dialog 2>/dev/null >/dev/null; then
     BrNewRel=$(dialog --rangebox Brightness -1 -1 0 100 "$BrCurRel" 3>&1 1>&2 2>&3)
+  else
+    abort "Could not find a program to request brightness from user. Please pass a positional argument." 1
   fi
+elif ! [[ "$BrNewRel" =~ $number_re ]]; then
+  abort "Invalid brightness '$BrNewRel', brightness must be an integer between 0 and 100" 2
 fi
 if [ -z "$BrNewRel" ]; then exit 1; fi
 
