Update source/.local/bin/contents Update source/.local/bin/dunnet Update source/.local/bin/post-temp Update source/.local/bin/steam

diff --git a/source/dot_local/exact_bin/executable_contents b/source/dot_local/exact_bin/executable_contents
--- a/source/dot_local/exact_bin/executable_contents
+++ b/source/dot_local/exact_bin/executable_contents
@@ -69,6 +69,9 @@ for file in "$@"; do
     continue
   fi
 
+  if ! command -v which &>/dev/null; then
+    abort 'Which is required to search PATH for files' 2
+  fi
   # given a name
   whichfile=$(which "$file" 2>/dev/null)
   if [ -f "$whichfile" ]; then
diff --git a/source/dot_local/exact_bin/executable_dunnet b/source/dot_local/exact_bin/executable_dunnet
--- a/source/dot_local/exact_bin/executable_dunnet
+++ b/source/dot_local/exact_bin/executable_dunnet
@@ -50,11 +50,11 @@ function parse_args() {
   exit 2
 }
 
-emacs="$(which emacs 2>/dev/null)"
 LONGOPTS=help,nosave,emacs:,save: SHORTOPTS=h,n,e:,s:
 ARGSTRING="$(parse_args "$@")"
 eval "$ARGSTRING"
 
+emacs=
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
@@ -65,6 +65,13 @@ while true; do
   *) abort "This is a bug" 3 ;;
   esac
 done
+
+if [ -z "$emacs" ]; then
+  if ! command -v which &>/dev/null; then
+    abort "which is required to search PATH for emacs. Please install which or provide the path via --emacs" 2
+  fi
+  emacs="$(which emacs 2>/dev/null)"
+fi
 
 # I don't know how to control emacs. just open dunnet pls
 if [ -z "$emacs" ] || ! [ -x "$emacs" ]; then
diff --git a/source/dot_local/exact_bin/executable_post-temp b/source/dot_local/exact_bin/executable_post-temp
--- a/source/dot_local/exact_bin/executable_post-temp
+++ b/source/dot_local/exact_bin/executable_post-temp
@@ -17,10 +17,11 @@ Usage: $THIS [OPTION...] [--] FILE...
 Hosts a temporary file on the internet for 60 mins and outputs the url.
 
 OPTIONS:
-  -h, --help       display this help message
-  -v, --verbose    display verbose messages
-  -q, --quiet      be quieter
-  -t, --temp=url   use url to upload files (POST) (default: $temp_source)
+  -h, --help         display this help message
+  -v, --verbose      display verbose messages
+  -q, --quiet        be quieter
+  -t, --temp=url     use url to upload files (POST) (default: $temp_source)
+  -p, --python=path  use path as python interpreter to parse json instead of searching PATH.
 EOF
   return 0
 }
@@ -53,11 +54,12 @@ function parse_args() {
 if [ "$#" -eq 0 ]; then usage && exit 0; fi
 
 verbose=false quiet=false
-LONGOPTS=help,verbose,quiet,temp:
-SHORTOPTS=h,v,q,t:
+LONGOPTS=help,verbose,quiet,python:,temp:
+SHORTOPTS=h,v,q,p:,t:
 ARGSTRING="$(parse_args "$@")"
 eval "$ARGSTRING"
 
+python=
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
@@ -65,6 +67,7 @@ while true; do
   -v | --verbose) verbose=true && shift ;; # Verbose option
   -q | --quiet) quiet=true && shift ;;     # Quiet option
   -t | --temp) temp_source="$2" && shift 2 ;;
+  -p | --python) python="$2" && shift 2 ;;
   *) abort "This is a bug" 3 ;;
   esac
 done
@@ -72,7 +75,12 @@ done
 # Error if args given, but no files given
 if [ "$#" -eq 0 ]; then abort "FILE is required!" 2; fi
 
-python=$(which python3 2>/dev/null || which python 2>/dev/null || printf '')
+if [ -z "$python" ]; then
+  if ! command -v which 2>/dev/null; then
+    abort "Which is required to find python in PATH. Please install which or provide the --python=path option." 2
+  fi
+  python=$(which python3 2>/dev/null || which python 2>/dev/null || printf '')
+fi
 declare -i exitcode=0
 
 for file in "$@"; do
diff --git a/source/dot_local/exact_bin/executable_steam b/source/dot_local/exact_bin/executable_steam
--- a/source/dot_local/exact_bin/executable_steam
+++ b/source/dot_local/exact_bin/executable_steam
@@ -18,6 +18,11 @@ get_nth_line() {
   printf '%s' "$line"
 }
 
+if ! command -v which &>/dev/null; then
+  echo "ERROR: which is required for this script." >&2
+  exit 1
+fi
+
 # Check if the current script is at the top of the PATH
 if [[ "$(realpath -- "$0")" = "$(which steam)" ]]; then
   # Finds all instances of 'steam' in PATH and returns the second line
