Update source/.local/bin/backup Add source/.vim/autoload/plug.vim

diff --git a/source/dot_local/exact_bin/executable_backup b/source/dot_local/exact_bin/executable_backup
--- a/source/dot_local/exact_bin/executable_backup
+++ b/source/dot_local/exact_bin/executable_backup
@@ -59,6 +59,8 @@ files=(
   "-$HOME/Downloads"
   "-$HOME/snap/*/*/.cache"
   "-$HOME/code/repos"
+  "-$HOME/Games/battlenet"
+  "-**/node_modules/**"
 )
 # Duplicity complains if an ignore pattern is not a subdirectory of the source directory
 if [ "$SOURCE_DIR" = / ]; then
@@ -102,7 +104,7 @@ if [ -z "$external" ] && [ -n "$usbname" ]; then
 fi
 
 if [ -z "$external" ]; then
-  printf '%s\n' "Could not find usb drive for backup. Please check that it's mounted." >&2
+  printf '%s\n' "$(date): Could not find usb drive for backup. Please check that it's mounted." >&2
   exit 1
 fi
 
