Update source/.local/bin/dunnet
Former-commit-id: 36da3a350bf0244f63ef84ef42e059eca95d5fdb
Former-commit-id: 738d951f9e73852089ac17caf1c6c0f9c5c14c79
Former-commit-id: 6fe1a15ae0a3f417073e6685bd554addf808929d

diff --git a/source/dot_local/exact_bin/executable_dunnet b/source/dot_local/exact_bin/executable_dunnet
--- a/source/dot_local/exact_bin/executable_dunnet
+++ b/source/dot_local/exact_bin/executable_dunnet
@@ -29,34 +29,40 @@ log() { printf '%s\n' "$@"; }
 err() { printf "$THIS: %s\n" "$@" >&2; }
 abort() { err "$1" && exit "${2:-1}"; }
 
-args=() emacs="$(which emacs 2>/dev/null)"
-# If awaiting an argument
-next='' next_arg='' end=false
-for arg; do
-  if [ $end = true ]; then
-    args+=("$arg")
-    continue
-  elif [ -n "$next" ]; then
-    declare -g "$next"="$arg"
-    next=''
-  else
-    case "$arg" in
-    --help | -h) usage && exit 0 ;;
-    --) end=true ;;
-    -n | --nosave) save_file='' ;;
-    -e | --emacs) next=emacs next_arg="$arg" ;;
-    --emacs=*) emacs="${arg#--emacs=}" ;;
-    -s | --save) next=save_file next_arg="$arg" ;;
-    --save=*) save_file="${arg#--save=}" ;;
-    --*) abort "Invalid option -- ${arg#-}" 2 ;;
-    -*) abort "Invalid option -- ${arg#-}" 2 ;;
-    *) args+=("$arg") ;;
-    esac
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
   fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+
+emacs="$(which emacs 2>/dev/null)"
+LONGOPTS=help,nosave,emacs:,save: SHORTOPTS=h,n,e:,s:
+eval "$(parse_args "$@")"
+
+while true; do
+  case "$1" in
+  --help | -h) usage && exit 0 ;;
+  --) shift && break ;;
+  -n | --nosave) save_file='' && shift ;;
+  -e | --emacs) emacs="$2" && shift 2 ;;
+  -s | --save) save_file="$2" && shift 2 ;;
+  *) abort "This is a bug" 3 ;;
+  esac
 done
-# If awaiting an argument, but end of args
-if [ -n "$next" ]; then abort "$next_arg requires an argument" 2; fi
-unset end next next_arg
 
 # I don't know how to control emacs. just open dunnet pls
 if [ -z "$emacs" ] || ! [ -x "$emacs" ]; then
@@ -74,7 +80,7 @@ if [ -n "$save_file" ]; then
 else
   printf '%s\n' "run 'save /path/to/dunnet.save' to overwrite save data (relative to CWD)"
 fi
-emacs_args+=("${args[@]}")
+emacs_args+=("$@")
 
 if [ -n "$save_file" ] && [ -f "$save_file" ]; then
   # save file exists, auto restore
