Update source/.local/bin/script_utils.sh Update source/.local/bin/snap-cleanup Update source/.local/bin/sort-files Update source/.local/bin/start-gdm Update source/.local/bin/steam Remove source/.local/bin/stop-gdm Update source/.local/bin/update-grub Update source/.local/bin/update-java Update source/.local/bin/visual Add source/.local/bin/stop-gdm

diff --git a/source/dot_local/exact_bin/executable_steam b/source/dot_local/exact_bin/executable_steam
--- a/source/dot_local/exact_bin/executable_steam
+++ b/source/dot_local/exact_bin/executable_steam
@@ -9,38 +9,26 @@
 # No argument parsing, as it's intended to be a transparent wrapper
 set -euC -o pipefail
 
-# usage 'get_nth_line 2', 1 indexed
-function get_nth_line() {
-  local _ line i
-  declare -i end="$1"
-  for ((i = 1; i < end; i++)); do read -r _; done || return 0
-  read -r line || return 0
-  printf '%s' "$line"
+# finds the first instance of cmd in path, excluding the current script
+function find_in_path() {
+  local path cmd exclude="${2:-${BASH_SOURCE[0]}}"
+  cmd=${1%/} cmd="${1##*/}" # remove trailing slash -- then get basename
+  while read -r -d: path; do
+    path=${path:-$PWD}                         # empty path means pwd
+    [ "$path/$cmd" != "$exclude" ] || continue # skip this_file
+    [ -x "$path/$cmd" ] || continue
+    printf '%s' "$path/$cmd" || true
+    return 0
+  done < <(printf '%s' "$PATH:")
+  printf '%s\n' "$cmd: command not found" >&2 || true
+  return 127
 }
-
-if ! command -v which &>/dev/null; then
-  printf '%s\n' "ERROR: which is required for this script." >&2
-  exit 1
-fi
-
-# Check if the current script is at the top of the PATH
-if [[ "$(realpath -- "$0")" = "$(which steam)" ]]; then
-  # Finds all instances of 'steam' in PATH and returns the second line
-  next_in_path=$(which -a steam 2>/dev/null | get_nth_line 2) || true
-else
-  # Find the first instance of 'steam' in PATH
-  next_in_path=$(which steam 2>/dev/null) || true
-fi
 
 # Checks flatpak first to see if it is installed.
 if flatpak info com.valvesoftware.Steam &>/dev/null; then
-  printf 'Running steam using flatpak from %s\n' "$0"
-  # Run the flatpak if installed
-  exec flatpak run com.valvesoftware.Steam "$@"
-elif [[ -n "$next_in_path" ]]; then
-  # Runs the other steam
-  exec "$next_in_path" "$@"
-else
-  printf '%s\n' "Could not find steam using Flatpak or PATH!"
-  exit 2
+  printf '%s\n' 'Running steam using flatpak' >&2 || true
+  exec -- flatpak run com.valvesoftware.Steam "$@" || exit
 fi
+
+next_in_path=$(find_in_path steam) || exit
+exec -- "$next_in_path" "$@"
diff --git a/source/dot_local/exact_bin/executable_update-java b/source/dot_local/exact_bin/executable_update-java
--- a/source/dot_local/exact_bin/executable_update-java
+++ b/source/dot_local/exact_bin/executable_update-java
@@ -5,130 +5,85 @@
 # Updates java symlinks to the path specified using update-alternatives
 #
 set -euC -o pipefail
+. script_utils.sh || exit
 
-THIS=update-java
 function usage() {
-  cat <<EOF
+  cat <<EOF || true
 $THIS [-y | --yes] <JAVADIR> [priority = 1112] [JVM_VERS_DIR]
 Updates java symlinks to the path specified using update-alternatives.
 Do not include /bin on JAVADIR.
 JVM_VERS_DIR will be determined by JAVA_HOME if set, or else default to /usr/lib/jvm
-
-
-the environment variable \`SUDO\` can be set to use a different
-program for root elevation. It will be split by the shell, so
-spaces in the program name will likely be mutilited.
+Note: relies on GNU find
 
 Options:
 -y, --yes     don't prompt for confirmation
 -q, --quiet   don't output debug info
 EOF
-  return 0
 }
-
-function log() { printf '%s\n' "$@"; }
-function err() { printf "${THIS:-$0}: %s\n" "$@" >&2; }
-function abort() {
-  err "$1"
-  exit "${2:-1}"
-}
-# use like `"${sudo[@]}" do_something`
-# shellcheck disable=SC2206 # Splitting is intentional.
-sudo=(${SUDO:-sudo})
-[ "$(id -u)" -eq 0 ] && sudo=()
-
-# Returns a string that should be 'eval'ed to set the positional arguments
-# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
-# Input: $LONGOPTS,$SHORTOPTS
-# eval "$(parse_args "$@")"
-function parse_args() {
-  local parsed
-  local code=0 && getopt --test &>/dev/null || code=$?
-  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
-  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
-    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
-  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
-}
-
 LONGOPTS=help,yes,quiet SHORTOPTS=h,y,q
 ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
 
-yes=0 quiet=0
+yes=0
 while true; do
   case "$1" in
   -h | --help) usage && exit 0 ;;
   -y | --yes) yes=1 && shift ;;
-  -q | --quiet) quiet=1 && shift ;;
+  -q | --quiet) USE_VERBOSE=0 && shift ;;
   --) shift && break ;;
   *) abort "This is a bug" 3 ;;
   esac
 done
 if [ "$#" -eq 0 ]; then usage && exit 2; fi
 
-function log_run() {
-  [ "$quiet" != 1 ] && log "$*"
-  "$@"
-}
-
 JAVADIR=${1:-}
 PRIORITY=${2:-1112}
 BINDIR=/usr/bin
-if [[ -n "${3:-}" ]]; then
+if [ -n "${3:-}" ]; then
   JVM_VERS_DIR=$3
-elif [[ -n "${JAVA_HOME:-}" ]]; then
+elif [ -n "${JAVA_HOME:-}" ]; then
   JVM_VERS_DIR=$(dirname -- "$JAVA_HOME") # /usr/lib/jvm/jdk-version --> /usr/lib/jvm
 else
   JVM_VERS_DIR=/usr/lib/jvm
 fi
 
-if ! [ -d "$JVM_VERS_DIR" ]; then
-  err "'$JVM_VERS_DIR' is not a directory. It will be created on confirmation" "$JVM_VERS_DIR"
-fi
-
-if ! [ -d "$JAVADIR" ]; then abort "'$JAVADIR' is not a directory" 2; fi
+[ -d "$JVM_VERS_DIR" ] || err "'$JVM_VERS_DIR' is not a directory. It will be created on confirmation" "$JVM_VERS_DIR"
+[ -d "$JAVADIR" ] || abort "'$JAVADIR' is not a directory" 2
 JAVADIR=$(realpath -- "$JAVADIR")
 
-if [[ "$JAVADIR" =~ ?(.*)/bin$ ]]; then
-  if [ "$yes" -eq 1 ]; then confirmation=yes; else
-    read -rep "$JAVADIR ends in /bin, would you like to use it's parent? (yes) " confirmation >&2
-  fi
-  if [[ -z "$confirmation" || "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
+case "$JAVADIR" in */bin)
+  if [ "$yes" -eq 1 ] || confirm "$JAVADIR ends in /bin, would you like to use it's parent?"; then
     JAVADIR=$(dirname -- "$(realpath -- "$JAVADIR")")
   fi
-fi
+  ;;
+esac
+[ "$yes" -eq 1 ] || confirm "Are you sure you would like to link all binaries in $JAVADIR?" || abort "Aborting" 1
 
-if ! [ "$yes" -eq 1 ]; then
-  read -rep "Are you sure you would like to link all binaries in $JAVADIR? (yes) " confirmation
-  if [[ -n "$confirmation" && ! "${confirmation,,}" =~ ^\s*y(es)?\s*$ ]]; then
-    abort "Aborting" 1
-  fi
-fi
-
-"${sudo[@]}" mkdir -p "$JVM_VERS_DIR"
+sudo_cmd mkdir -p "$JVM_VERS_DIR"
 JVM_VERS_DIR=$(realpath -- "$JVM_VERS_DIR")
 
-if [[ $(dirname -- "$JAVADIR") != "$JVM_VERS_DIR" ]]; then
-  err "Copying files to '$JVM_VERS_DIR'"
-  "${sudo[@]}" cp --archive --interactive "$JAVADIR" "$JVM_VERS_DIR"
+if [ "$(dirname -- "$JAVADIR")" != "$JVM_VERS_DIR" ]; then
+  log "Copying files to '$JVM_VERS_DIR'"
+  # cp -PpR is posix for cp --archive
+  sudo_cmd cp -PpRi -- "$JAVADIR" "$JVM_VERS_DIR/"
   JAVADIR="$JVM_VERS_DIR/$(basename -- "$JAVADIR")"
 fi
 
 function link() {
-  dest_path=$1 name=$2 from_path=$3 priority=$4
-  if command -v update-alternatives &>/dev/null; then
-    log_run "${sudo[@]}" update-alternatives --install "$dest_path" "$name" "$from_path" "$priority"
-    log_run "${sudo[@]}" update-alternatives --set "$name" "$from_path"
-  else
+  local dest_path=$1 name=$2 from_path=$3 priority=$4
+  if ! has_cmd update-alternatives; then
     # use ln because update-alternatives is not available
-    log_run "${sudo[@]}" ln -sf -T "$from_path" "$dest_path"
+    verbose sudo_cmd ln -sf -T "$from_path" "$dest_path"
+    return 0
   fi
+  verbose sudo_cmd update-alternatives --install "$dest_path" "$name" "$from_path" "$priority"
+  verbose sudo_cmd update-alternatives --set "$name" "$from_path"
 }
 
-while read -d $'\0' -sr from_path; do
+while read -d '' -r -s from_path; do
   name=$(basename -- "$from_path")
   dest_path="$BINDIR/$name"
   link "$dest_path" "$name" "$from_path" "$PRIORITY"
 done < <(find "$JAVADIR" -perm /u=x,g=x,o=x -type f -print0)
 
-log_run "${sudo[@]}" ln -sf -T "$JAVADIR" "$JVM_VERS_DIR/default-java"
+verbose sudo_cmd ln -sf -T "$JAVADIR" "$JVM_VERS_DIR/default-java"
 unset -v cmd
diff --git a/source/dot_local/exact_bin/executable_visual b/source/dot_local/exact_bin/executable_visual
--- a/source/dot_local/exact_bin/executable_visual
+++ b/source/dot_local/exact_bin/executable_visual
@@ -14,25 +14,25 @@ EOF
 }
 
 function log() { printf '%s\n' "$@" || true; }
-function err() { printf "${THIS:-}: %s\n" "$@" >&2 || true; }
+function err() { printf "%s\n" "$@" >&2 || true; }
 function abort() { err "$1" && exit "${2:-1}"; }
-function cmd() { command -v "$@" &>/dev/null; }
+function has_cmd() { command -v "$@" &>/dev/null; }
+function cmd_path() { command -v "$@"; }
+function first_cmd() {
+  local c && for c; do
+    has_cmd "$c" || continue
+    printf '%s' "$c" || true
+    return 0
+  done
+  return 1
+}
 function verbose() {
-  local cmd=("$@")
-  { # output the command with quotes!
-    local i=0
-    for c in "${cmd[@]}"; do
-      printf "'%s'" "$c"
-      if [ "$i" -lt "${#cmd}" ]; then printf ' '; fi # space except last time.
-      i=$((i + 1))
-    done
-    printf '\n'
-  } || true
-  "${cmd[@]}"
+  printf '%s\n' "> ${*@Q}" || true
+  "$@"
 }
 
-if ! cmd which; then abort "which is required for this script" 1; fi
-if ! cmd startx; then abort "startx is required for this script" 1; fi
+has_cmd which || abort "which is required for this script" 1
+has_cmd startx || abort "startx is required for this script" 1
 
 for arg in "$@"; do
   case "$arg" in
@@ -44,46 +44,38 @@ wm=${1:-}
 server=${2-}
 rest=("${@:3}")
 
-disp_regex="^:[[:digit:]]+$"
+is_integer() { [ -n "$1" ] && case "$1" in *[!0123456789]*) return 1 ;; esac }
+# returns true if the argument is a valid display number (:integer)
+is_display() { [ -n "$1" ] && [ "${1:0:1}" == ":" ] && is_integer "${1#:}"; }
 
 # visual -- [:3] --server-args
 if [ "$wm" == '--' ]; then
-  wm=
-  server=--
+  wm='' server=--
   rest=("${@:2}") # [:3] --server-args
 fi
 
 # visual :3
-if [ -z "$server" ] && [[ "$wm" =~ $disp_regex ]]; then server="$wm" wm=''; fi
+if [ -z "$server" ] && is_display "$wm"; then server="$wm" wm=''; fi
 
 # visual :3 OR visual awesome
-if [ -z "$wm" ]; then
-  if [ -x "$(command -v x-window-manager)" ]; then
-    wm=x-window-manager
-  elif [ -x "$(command -v x-terminal-emulator)" ]; then
-    wm=x-terminal-emulator
-  fi
-fi
+[ -n "$wm" ] || wm=$(first_cmd x-window-manager x-terminal-emulator)
 
-if wmpath=$(which "$wm" 2>/dev/null); then :; else
-  abort "Unable to find $wm in \$PATH" 2
-fi
-
+wmpath=$(cmd_path "$wm") || abort "$wm: command not found" 2
+cmd=()
 # HACK: startx on ubuntu still unsets DBUS_SESSION_BUS_ADDRESS (even though it's fixed in upstream)
 # IF this is the case, call it again with *this* script as the wm.
-if [ -n "${__IN_VISUAL_SPAWN:-}" ]; then
-  cmd=("$wmpath")
-elif grep -q 'unset DBUS_SESSION_BUS_ADDRESS' "$(which startx)"; then
-  export __IN_VISUAL_SPAWN=1
-  cmd=(startx "$0" "$wmpath")
-else
-  cmd=(startx "$wmpath")
+if [ -z "${__IN_VISUAL_SPAWN:-}" ]; then
+  startx=$(cmd_path startx) || abort "startx: command not found" 1
+  cmd=("$startx")
+  if grep -q 'unset DBUS_SESSION_BUS_ADDRESS' "$startx"; then
+    export __IN_VISUAL_SPAWN=1
+    cmd+=("${BASH_SOURCE[0]}")
+  fi
 fi
+cmd+=("$wmpath")
 
 # if server is defined
-if [[ "$server" =~ $disp_regex ]]; then
-  cmd+=(--)
-fi
+if is_display "$server"; then cmd+=(--); fi
 if [ -n "$server" ]; then cmd+=("$server"); fi
 cmd+=("${rest[@]}")
 
@@ -105,8 +97,7 @@ fi
 if [ -z "${XAUTHORITY:-}" ] && [ -d "${XDG_RUNTIME_DIR:-}" ]; then
   # NOTE: this path was chosen because in Ubuntu, it is permitted in the AppArmor config. See /etc/apparmor.d/abstractions/X.
   export XAUTHORITY="$XDG_RUNTIME_DIR/X11/Xauthority"
-  mkdir -p "$(dirname "$XAUTHORITY")" # Ensure the directory exists
+  mkdir -p -- "$(dirname "$XAUTHORITY")" # Ensure the directory exists
 fi
 
-# export XDG_SESSION_TYPE=x11
 verbose exec "${cmd[@]}"
