Update source/.local/bin/start-gdm
Former-commit-id: 25b5c8463f1905149c8501c350fe50227af0da23
Former-commit-id: d4b23cd18661f8235ac9581dbf39d74580b83603
Former-commit-id: 1d82f6b6392f1f09a46e298956117e09ee8a7493

diff --git a/source/dot_local/exact_bin/executable_start-gdm b/source/dot_local/exact_bin/executable_start-gdm
--- a/source/dot_local/exact_bin/executable_start-gdm
+++ b/source/dot_local/exact_bin/executable_start-gdm
@@ -1,3 +1,51 @@
 #!/usr/bin/env bash
+# This sets systemd to hide it's status, shows plymouth on shutdown, and starts gdm through systemd graphical.target
+
+THIS=start-gdm
+
+usage() {
+  cat <<-EOF
+usage: $THIS 
+
+Sets systemd to hide it's status, shows plymouth on shutdown, and starts gdm through systemd graphical.target
+No options or arguments are accepted except --help
+EOF
+}
+
+for arg; do
+  case "$arg" in
+  --help | -help | -h) usage && exit 0 ;;
+  esac
+done
+
 set -eu
-systemctl isolate graphical.target
+log() { printf '%s\n' "$@"; }
+err() { printf "$THIS: %s\n" "$@" >&2; }
+abort() { err "$1" && exit "${2:-1}"; }
+
+remove_from_file() {
+  local file=$1
+  local remove=("${@:2}")
+  local args=()
+  for word in "${remove[@]}"; do
+    args+=(-e "s/\b$word\b//g")
+  done
+  sed "$file" "${args[@]}" # output
+}
+concat() { printf '%s ' "$@"; }
+
+tmp_file="$(mktemp)" || abort "Error making tmp file"
+trap 'rm -f "$tmp_file"' EXIT
+
+sudo kill -s SIGRTMIN+21 1 || abort "Error setting systemd to hide status"
+# reads from mount if present
+concat "$(remove_from_file /proc/cmdline 'splash' 'nosplash' 'plymouth.enable=0')" "splash" >|"$tmp_file"
+# This fails if not a mount
+sudo umount /proc/cmdline -q || true
+sudo mount -n --bind -o ro "$tmp_file" /proc/cmdline || abort 'Failed to make bind mount on /proc/cmdline'
+
+# Cleanup
+rm -f "$tmp_file" && trap '' EXIT
+
+# start the graphical system
+exec systemctl isolate graphical.target
