Update source/.local/bin/rmgit
Former-commit-id: dcae391ac82dcace7420bd0ddac934d22b0195af
Former-commit-id: c12aa2f6aab9fe9e740ade6c3a4e961c87059782
Former-commit-id: 534f51e049839e6e182b8b51c58de68f27adb618

diff --git a/source/dot_local/exact_bin/executable_rmgit b/source/dot_local/exact_bin/executable_rmgit
--- a/source/dot_local/exact_bin/executable_rmgit
+++ b/source/dot_local/exact_bin/executable_rmgit
@@ -44,6 +44,10 @@ done
 shift "$((OPTIND - 1))"
 
 REPO=$1
+if [ -z "$REPO" ]; then
+  err "REPO is required"
+  exit 2
+fi
 
 if ! [ -d "$REPO" ] || ! [ -d "$REPO"/.git ]; then
   err "$REPO is not a git repository"
