Update source/.local/bin/colors Update source/.local/bin/script_utils.sh
Former-commit-id: 122d693a2384801bc52fa292990a205366cdea31
Former-commit-id: eedf628091745ebb9bba624b4fc2dd3adf897039
Former-commit-id: ec22071086a697015197ec06418c1302f76b6f13

diff --git a/source/dot_local/exact_bin/executable_colors b/source/dot_local/exact_bin/executable_colors
--- a/source/dot_local/exact_bin/executable_colors
+++ b/source/dot_local/exact_bin/executable_colors
@@ -33,13 +33,36 @@ abort() {
 }
 
 ## PARSE ARGS #############################
+# Returns a string that should be 'eval'ed to set the positional arguments
+# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
+# Input: $LONGOPTS,$SHORTOPTS
+# eval "$(parse_args "$@")"
+function parse_args() {
+  # -allow a command to fail with !’s side effect on errexit
+  # -use return value from ${PIPESTATUS[0]}, because ! hosed $?
+  # shellcheck disable=SC2251
+  ! getopt --test >/dev/null
+  if [[ "${PIPESTATUS[0]}" -ne 4 ]]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
+
+  local parsed
+  if parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS-$0}" -- "$@"); then
+    # output getopt’s output this way to handle the quoting right:
+    printf '%s' "set -- $parsed"
+    return 0
+  fi
+  # getopt has already complained about wrong arguments to stdout - Exit script
+  exit 2
+}
+
+LONGOPTS=help SHORTOPTS=h
+ARGSTRING="$(parse_args "$@")"
+eval "$ARGSTRING"
+
 for arg; do
   case "$arg" in
-  --help | -h | -\?) usage && exit 0 ;;
-  --) break ;;
-  # Invalid -flag
-  --*) abort "invalid option -- '${arg#--}'" 2 ;;
-  -*) abort "invalid option -- '${arg#-}'" 2 ;;
+  --help | -h) usage && exit 0 ;;
+  --) shift && break ;;
+  *) abort "This is a bug" 3 ;;
   esac
 done
 
