Update source/.local/bin/brightness

diff --git a/source/dot_local/exact_bin/executable_brightness b/source/dot_local/exact_bin/executable_brightness
--- a/source/dot_local/exact_bin/executable_brightness
+++ b/source/dot_local/exact_bin/executable_brightness
@@ -5,7 +5,7 @@ set -euC -o pipefail
 THIS="brightness"
 
 function usage() {
-  cat <<-EOF
+  cat || true <<-EOF
 usage: $THIS [OPTS]... [percent]
 Sets the brightness to the specified integer percentage. Use n{+,-} to increment the brightness.
 Without a percentage, outputs the current brightness percentage
@@ -21,8 +21,8 @@ Options:
 EOF
 }
 
-function log() { printf '%s\n' "$@"; }
-function err() { printf "$THIS: %s\n" "$@" >&2; }
+function log() { printf '%s\n' "$@" || true; }
+function err() { printf "$THIS: %s\n" "$@" >&2 || true; }
 function abort() { err "$1" && exit "${2:-1}"; }
 number_re='^[0-9]+$'
 function is_integer() { [[ "$1" =~ $number_re ]]; }
@@ -82,29 +82,25 @@ if [ "$BrMax" -eq 0 ]; then abort "Backlight device reported maximum brightness 
 
 BrCurRel="$(printf '%s ' "$BrCur" "$BrMax" | awk '{ print int( $1 / $2 * 100 ) }')"
 
-if [ "$show" = true ]; then
-  log "$BrCurRel"
-else
-  BrNewRel="${1:-}"
-  if [ -z "$BrNewRel" ]; then abort "Brightness can't be empty" 2; fi
-  suf='' BrNewRel=${1}
-  case "$BrNewRel" in
-  +* | *+) suf=+ ;;
-  -* | *-) suf=- ;;
-  esac
-  BrNewRel=${BrNewRel%-} BrNewRel=${BrNewRel#-} BrNewRel=${BrNewRel%+} BrNewRel=${BrNewRel#+} BrNewRel=${BrNewRel%\%}
-  if ! is_integer "$BrNewRel"; then abort "Invalid brightness '$BrNewRel'" 2; fi
-  case "$suf" in
-  +) BrNewRel=$((BrCurRel + BrNewRel)) ;;
-  -) BrNewRel=$((BrCurRel - BrNewRel)) ;;
-  esac
+if [ "$show" = true ]; then log "$BrCurRel" && exit 0; fi
 
-  BrNew="$(printf '%s ' "$BrNewRel" "$BrMax" | awk '{ print int( ( ($1/100) * $2) ) }')"
-  BrNew="$((BrNew < BrMin ? BrMin : BrNew))"
-  BrNew="$((BrNew > BrMax ? BrMax : BrNew))"
+BrNewRel="${1:-}" && if [ -z "$BrNewRel" ]; then abort "Brightness can't be empty" 2; fi
+suf='' && case "$BrNewRel" in
++* | *+) suf=+ ;;
+-* | *-) suf=- ;;
+esac
+BrNewRel=${BrNewRel%-} BrNewRel=${BrNewRel#-} BrNewRel=${BrNewRel%+} BrNewRel=${BrNewRel#+} BrNewRel=${BrNewRel%\%}
+if ! is_integer "$BrNewRel"; then abort "Invalid brightness '$BrNewRel'" 2; fi
+case "$suf" in
++) BrNewRel=$((BrCurRel + BrNewRel)) ;;
+-) BrNewRel=$((BrCurRel - BrNewRel)) ;;
+esac
 
-  sudo=()
-  if ! [ -w "$BrPath"/brightness ]; then sudo=("${SUDO:-sudo}"); fi
+BrNew="$(printf '%s ' "$BrNewRel" "$BrMax" | awk '{ print int( ( ($1/100) * $2) ) }')"
+BrNew="$((BrNew < BrMin ? BrMin : BrNew))"
+BrNew="$((BrNew > BrMax ? BrMax : BrNew))"
 
-  printf '%s' "$BrNew" | "${sudo[@]}" tee "$BrPath/brightness" >/dev/null
-fi
+sudo=()
+if ! [ -w "$BrPath"/brightness ]; then sudo=("${SUDO:-sudo}"); fi
+
+printf '%s' "$BrNew" | "${sudo[@]}" tee "$BrPath/brightness" >/dev/null
