Update source/.local/bin/update Add source/.bashrc.d/30_functions/textimage Update source/.config/git/config Update source/.config/git/alias-wrapper.sh Update source/.config/gtk-2.0/gtkfilechooser.ini Update source/.config/htop/htoprc

diff --git a/source/dot_local/exact_bin/executable_update b/source/dot_local/exact_bin/executable_update
--- a/source/dot_local/exact_bin/executable_update
+++ b/source/dot_local/exact_bin/executable_update
@@ -92,6 +92,15 @@ for arg; do # Doesn't do anything if $# is zero
     ;;
   esac
 done
+function repeat() {
+  local err=0
+  while true; do
+    "$@" || err=$?
+    [ "$err" != 0 ] || return 0 # success
+    err "Command failed: ${*@Q}"
+    confirm "Try again?" || return "$err"
+  done
+}
 
 to_update=()
 for m in "${!methods[@]}"; do
