Update source/.local/bin/backup

diff --git a/source/dot_local/exact_bin/executable_backup b/source/dot_local/exact_bin/executable_backup
--- a/source/dot_local/exact_bin/executable_backup
+++ b/source/dot_local/exact_bin/executable_backup
@@ -275,9 +275,9 @@ fi
 # ----------------------------------------------------------------
 
 function verbose() {
-  local verbose=${BACKUP_VERBOSE:-}             # if BACKUP_VERBOSE, be verbose
-  [ -z "${BACKUP_DRY_RUN:-}" ] || verbose=1     # if dry-run, be verbose
-  [ -z "$verbose" ] || printf "%s\n" "> ${*@Q}" # print it
+  local verbose=${BACKUP_VERBOSE:-}                 # if BACKUP_VERBOSE, be verbose
+  [ -z "${BACKUP_DRY_RUN:-}" ] || verbose=1         # if dry-run, be verbose
+  [ -z "$verbose" ] || printf "%s\n" "> ${*@Q}" >&2 # print it
 
   [ -z "${BACKUP_DRY_RUN:-}" ] || return 0
   "$@" # run it
@@ -341,36 +341,65 @@ esac
 # usage: prefix echo <<<"hello world"
 # output: 'echo' 'hello world'
 prefix() {
-  awk -v prefix="${*@Q} " '{print $prefix$0}'
+  awk -v prefix="${*@Q} " '{print prefix $0}'
+}
+
+# like declare -p, but nicer output
+print_array() {
+  for name in "$@"; do
+    declare -n array="$name"
+    local array=("${array[@]}")
+    printf '%s\n' "declare -${array@a} $name=("
+    printf '  %s %s %s %s\n' "${array[@]@Q}"
+    printf ')\n'
+  done
 }
 
 function list_packages() {
-  local pkg_manager
+  printf '%s\n' "#!/usr/bin/env bash"
+  printf '%q ' printf '%s\n' "set -euC -o pipefail" && printf '\n'
+  printf '%q ' printf '%s\n' "Installing packages from backup..." && printf '\n'
   # Note: Order matters!
   local pkg_managers=(
     yay paru pacman # Arch / Manjaro
     apt             # Debian / Ubuntu
   )
+  local pkg_manager
   pkg_manager="$(first_cmd "${pkg_managers[@]}")" || true
   case "$pkg_manager" in
   yay | paru | pacman)
     local args=(-Qq)
     [ "$pkg_manager" != pacman ] || args+=(-n) # only show native packages if using pacman
-    "$pkg_manager" "${args[@]}" -e | prefix "$pkg_manager" -S --needed --asexplicit --
-    "$pkg_manager" "${args[@]}" -d | prefix "$pkg_manager" -S --needed --asdeps --
+    # shellcheck disable=SC2034
+    {
+      local explicit_deps=() auto_deps=()
+      mapfile -t explicit_deps < <("$pkg_manager" "${args[@]}" -e)
+      mapfile -t auto_deps < <("$pkg_manager" "${args[@]}" -d)
+      print_array explicit_deps auto_deps
+    }
+
+    printf '%s\n' "${pkg_manager@Q} -S --needed --asexplicit -- \"\${explicit_deps[@]}\""
+    printf '%s\n' "${pkg_manager@Q} -S --needed --asdeps -- \"\${auto_deps[@]}\""
     ;;
   apt)
     has apt-mark || abort "apt-mark is not installed. Please install it" 3
-    apt-mark showmanual | prefix apt install --
-    apt-mark showauto | prefix apt install --mark-auto --
+    # shellcheck disable=SC2034
+    {
+      local explicit_deps=() auto_deps=()
+      mapfile -t explicit_deps < <(apt-mark showmanual)
+      mapfile -t auto_deps < <(apt-mark showauto)
+      print_array explicit_deps auto_deps
+    }
+
+    printf '%s\n' "${pkg_manager@Q} install -- \"\${explicit_deps[@]}\""
+    printf '%s\n' "${pkg_manager@Q} install --mark-auto -- \"\${auto_deps[@]}\""
     ;;
-  # aptitude) aptitude search '~i !~M' -F '%p' ;;
-  # apt) apt list --manual-installed | cut -d/ -f1 ;; # worst case; apt does not have a stable CLI interface.
   '') err "Could not determine package manager. To add support, add a case statement to list_pacakges()" ;;
   # This means it was added to the list of package managers but not the case statement
   *) abort "Unknown package manager '$pkg_manager'. This is most likely a bug." 3 ;;
   esac
 }
+
 case "$mode" in
 backup)
   log ''
