Update source/.local/bin/post-temp

diff --git a/source/dot_local/exact_bin/executable_post-temp b/source/dot_local/exact_bin/executable_post-temp
--- a/source/dot_local/exact_bin/executable_post-temp
+++ b/source/dot_local/exact_bin/executable_post-temp
@@ -6,13 +6,12 @@
 #
 #
 set -euC -o pipefail
+. script_utils.sh || exit
 
-THIS='post-temp'
 temp_source=https://tmpfiles.org/api/v1/upload
 
 function usage() {
-
-  cat <<EOF
+  cat <<EOF || true
 Usage: $THIS [OPTION...] [--] FILE...
 Hosts a temporary file on the internet for 60 mins and outputs the url.
 
@@ -23,72 +22,40 @@ OPTIONS:
   -t, --temp=url     use url to upload files (POST) (default: $temp_source)
   -p, --python=path  use path as python interpreter to parse json instead of searching PATH.
 EOF
-  return 0
 }
-function log() { printf '%s\n' "$@"; }
-function err() { printf "%s\n" "$@" >&2; }
-function abort() { err "$1" && exit "${2:-1}"; }
-
-# Returns a string that should be 'eval'ed to set the positional arguments
-# Store the string in a variable (ie ARGSTRING) to maintain the exit code if parse_args fails.
-# Input: $LONGOPTS,$SHORTOPTS
-# eval "$(parse_args "$@")"
-function parse_args() {
-  local parsed
-  local code=0 && getopt --test &>/dev/null || code=$?
-  if [ "$code" -ne 4 ]; then abort "Enhanced getopt is required for this script to work. Please install it." 1; fi
-  parsed=$(getopt --options="$SHORTOPTS" --longoptions="$LONGOPTS" --name "${THIS:-$0}" -- "$@") ||
-    exit 2                     # getopt has already complained about wrong arguments to stdout - Exit script
-  printf '%s' "set -- $parsed" # output getopt’s output this way to handle the quoting right
-}
-
-# Usage if no args are passed
-if [ "$#" -eq 0 ]; then usage && exit 0; fi
-
-verbose=false quiet=false
 LONGOPTS=help,verbose,quiet,python:,temp: SHORTOPTS=h,v,q,p:,t:
 ARGSTRING="$(parse_args "$@")" && eval "$ARGSTRING" || exit
 
-python=
+verbose=0 quiet=0 python=
 while true; do
   case "$1" in
   --help | -h) usage && exit 0 ;;
   --) shift && break ;;
-  -v | --verbose) verbose=true && shift ;; # Verbose option
-  -q | --quiet) quiet=true && shift ;;     # Quiet option
+  -v | --verbose) verbose=1 && shift ;; # Verbose option
+  -q | --quiet) quiet=1 && shift ;;     # Quiet option
   -t | --temp) temp_source="$2" && shift 2 ;;
   -p | --python) python="$2" && shift 2 ;;
   *) abort "This is a bug" 3 ;;
   esac
 done
 
-# Error if args given, but no files given
-if [ "$#" -eq 0 ]; then abort "FILE is required!" 2; fi
+[ "$#" -gt 0 ] || abort "FILE is required!" 2 # Error if no files given
 
-if [ -z "$python" ]; then
-  if ! command -v which >/dev/null 2>/dev/null; then
-    abort "Which is required to find python in PATH. Please install which or provide the --python=path option." 2
-  fi
-  python=$(which python3 2>/dev/null || which python 2>/dev/null || printf '')
-fi
+[ -n "$python" ] || python=$(cmdpath python3 || cmdpath python) || true
+
 declare -i exitcode=0
-
 for file in "$@"; do
-  if ! [[ -f "$file" ]]; then
-    err "'$file' is not a file"
-    exitcode=2 && continue
-  fi
+  [ -f "$file" ] || abort "'$file' is not a file" 1
 
-  result="$(curl -L -F "file=@$file" "$temp_source")" ||
-    err 'Something went wrong during curl command.'
+  result="$(curl -L -F "file=@$file" "$temp_source")" || abort 'Something went wrong during curl command.' 1
   # Example outputs:
   # {"message": "server error"}
   # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}
 
   # If verbose, or python not installed, print entire json
-  if [ "$verbose" = true ] || [ -z "$python" ]; then
+  if [ "$verbose" = 1 ] || [ -z "$python" ]; then
     log "$result"
-    [ -z "$python" ] && continue # Stops loop here because python is not installed
+    [ -n "$python" ] || continue # Stops loop here because python is not installed
   fi
 
   # Print the result thru python to get the data
@@ -100,7 +67,7 @@ for file in "$@"; do
     if [ -n "$message" ]; then err "$message"; else err "An unknown error occured"; fi
     exitcode=1
   else
-    [ "$quiet" != true ] && err "$status"
+    [ "$quiet" == 1 ] || err "$status"
     log "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
   fi
 done
