Update source/.local/bin/contents
Former-commit-id: 3d00b38e20852dcc0ff7b7ee8e31de77dda7f571
Former-commit-id: 3309b2ecf9669d8cfe274ed948c22ba5e3284444
Former-commit-id: aa37af92781a6a447133c9f8b24351e4e69d36f1

diff --git a/source/dot_local/exact_bin/executable_contents b/source/dot_local/exact_bin/executable_contents
--- a/source/dot_local/exact_bin/executable_contents
+++ b/source/dot_local/exact_bin/executable_contents
@@ -36,6 +36,11 @@ EOF
 done
 unset end
 
+if [ $# -eq 0 ]; then
+  err 'FILE is required'
+  exit 1
+fi
+
 files=()
 for file in "${args[@]}"; do
   # Given a path
