Update source/.local/bin/gradlew

diff --git a/source/dot_local/exact_bin/executable_gradlew b/source/dot_local/exact_bin/executable_gradlew
--- a/source/dot_local/exact_bin/executable_gradlew
+++ b/source/dot_local/exact_bin/executable_gradlew
@@ -8,37 +8,38 @@ function log() { printf '%s\n' "$@" || true; }
 function abort() { err "$1" && exit "${2:-1}"; }
 
 command -v dirname >/dev/null 2>&1 || abort "dirname is not installed." 127
-
-build_gradle=""
-curr="${PWD}"
-# First, search recursively upwards for a build.gradle.
-until [ "$curr" == "/" ]; do
-  for name in "${BUILD_GRADLE[@]}"; do
-    [ -e "${curr}/$name" ] || continue
-    build_gradle="$curr/$name"
-    break 2
+search_upwards() {
+  local dir="$1" names=("${@:2}")
+  local name
+  while [ "$dir" != "/" ]; do
+    for name in "${names[@]}"; do
+      [ -e "${dir}/$name" ] || continue
+      printf '%s\n' "$dir/$name"
+      return 0
+    done
+    dir=$(dirname -- "$dir")
   done
-  curr=$(dirname -- "$curr")
-done
-[ -n "$build_gradle" ] || abort "Unable to find a ${BUILD_GRADLE[0]} in any parent directory." 1
+  return 1
+}
 
-gradlew=''
-# Search recursively upwards from the first-found build.gradle for a gradlew.
-until [ "$curr" == "/" ]; do
-  if [ -x "$curr/gradlew" ]; then
-    gradlew="${curr}/gradlew"
-    break
-  fi
-  curr=$(dirname "${curr}")
-done
+dir=$(pwd)
+if [ -x "$dir/gradlew" ]; then
+  log "Found a gradlew wrapper script in the current directory."
+  gradlew="$dir/gradlew"
+  cd -- "$(dirname -- "$gradlew")"
+  exec -- "$gradlew" "$@"
+fi
 
+build_gradle=$(search_upwards "$dir" "${BUILD_GRADLE[@]}") || abort "Unable to find a ${BUILD_GRADLE[0]} in any parent directory."
+dir=$(dirname -- "$build_gradle") # search from build.gradle's location
+{ gradlew=$(search_upwards "$dir" "gradlew") && [ -x "$gradlew" ]; } || abort "Unable to find an executable gradlew in any parent directory."
+
+gradle_type="wrapper"
 # Select the right gradle or error out if no good options exist.
-if [ -n "$gradlew" ]; then
-  gradle_type="wrapper"
-else
+if [ -z "$gradlew" ]; then
+  gradle_type="executable"
   # Find the system gradle executable to fall back on.
   gradlew=$(command -v gradle 2>/dev/null) || abort "Unable to find a gradlew or gradle."
-  gradle_type="executable"
   log "There is no gradlew set up for this project. You may want to consider setting one up."
   log "See: http://gradle.org/docs/current/userguide/gradle_wrapper.html"
 fi
