update pnpm
Also remove wget dependency, as pnpm doesn't depend on wget? This may be a mistake. Testing is needed.

diff --git a/source/.chezmoiscripts/10-install/run_onchange_after_10-pnpm.sh.tmpl b/source/.chezmoiscripts/10-install/run_onchange_after_10-pnpm.sh.tmpl
--- a/source/.chezmoiscripts/10-install/run_onchange_after_10-pnpm.sh.tmpl
+++ b/source/.chezmoiscripts/10-install/run_onchange_after_10-pnpm.sh.tmpl
@@ -15,22 +15,25 @@ function add_global_dir_to_path() {
   local global_bin_dir
   global_bin_dir="$(pnpm config get global-bin-dir 2>/dev/null || printf '')"
   if [ -z "$global_bin_dir" ]; then return 1; fi
-  if [[ ":$PATH:" = *:"$global_bin_dir":* ]]; then return 0; fi
-  PATH="$PATH:$global_bin_dir"
+  case ":$PATH:" in
+  *:"$global_bin_dir":*) return 0 ;;
+  *) PATH="$PATH:$global_bin_dir" ;;
+  esac
 }
 
+URL=https://raw.githubusercontent.com/tj/n/master/bin/n
 function install_pnpm_and_node() {
-  local tmp=$(mktmp)
-  trap 'rm -f "$tmp"' EXIT
+  local tmp
   log 'installing n'
-  curl -fsSL https://raw.githubusercontent.com/tj/n/master/bin/n -o "$tmp"
+  tmp=$(download_file "$URL")
+  rm_exit "$tmp"
   log 'installing node lts through n...'
   (
     export -n SHELLOPTS
     # NOTE: latest is needed on my machine to avoid EHOSTUNREACH from npm repos
     sudo bash "$tmp" latest
   )
-  rm -f "$tmp" && trap '' EXIT # cleanup
+  rm_exit_cleanup "$tmp"
 
   # Setup pnpm
   log 'installing pnpm'
@@ -49,16 +52,16 @@ install_pnpm_global_packages() {
   pnpm i -g n
 }
 
-if ! is_accessible_cmd wget; then
-  err "wget is not present, attempting to install."
-  if [ -n "$APT" ]; then
-    sudo "$APT" install wget
-  elif [ -n "$PACMAN" ]; then
-    sudo "$PACMAN" -S --needed -- wget
-  else
-    abort "wget is required to install n. Please install it and try again." 1
-  fi
-fi
+# if ! is_accessible_cmd wget; then
+#   err "wget is not present, attempting to install."
+#   if [ -n "$APT" ]; then
+#     apt_install wget
+#   elif [ -n "$PACMAN" ]; then
+#     sudo "$PACMAN" -S --needed -- wget
+#   else
+#     abort "wget is required to install n. Please install it and try again." 1
+#   fi
+# fi
 
 is_accessible_cmd pnpm || log_and_run 'Installing NodeJS and pnpm' install_pnpm_and_node
 is_accessible_cmd pnpm && log_and_run 'Installing pnpm global packages' install_pnpm_global_packages
