Update source/.bashrc.d/30_functions/exitall
Former-commit-id: 2278a9f0bb7d6a8bff75b721c6343e4f9e5c2013
Former-commit-id: db5570e865e5b5660208d40be9cf80e785ced0a6
Former-commit-id: cedcab1580201230a7e9aa7582c38c639b6b9187

diff --git a/source/exact_dot_bashrc.d/exact_30_functions/exitall b/source/exact_dot_bashrc.d/exact_30_functions/exitall
--- a/source/exact_dot_bashrc.d/exact_30_functions/exitall
+++ b/source/exact_dot_bashrc.d/exact_30_functions/exitall
@@ -26,11 +26,12 @@ bash() {
 
 exit() { exitall "$@"; }
 exitall() {
+  exit_code=$?
   [[ ! $(caller 0) ]] && set -- all # if exitall called directly, set $1 to all
   if [[ ${1,,} == "all" ]]; then    #if first argument is "all"
     builtin exit 196 2>/dev/null    # code to close recursively
   else
+    (exit "$exit_code")           # preserve exit code if none provided
     builtin exit "$@" 2>/dev/null # passthrough argument to exit
   fi
 }
-export -f "bash" "exit" "exitall"
