Update source/.bashrc.d/30_functions/exitall
Former-commit-id: 786b260d1e01e585ba65221b7f37a1690e9f6962
Former-commit-id: 59a42006598a64137cd02fe88878d94387a6dea9
Former-commit-id: 52eb43e6a3198666ef2a8f3dd4d016b985d94ff9

diff --git a/source/exact_dot_bashrc.d/exact_30_functions/exitall b/source/exact_dot_bashrc.d/exact_30_functions/exitall
--- a/source/exact_dot_bashrc.d/exact_30_functions/exitall
+++ b/source/exact_dot_bashrc.d/exact_30_functions/exitall
@@ -31,7 +31,7 @@ exitall() {
   if [[ ${1,,} == "all" ]]; then    #if first argument is "all"
     builtin exit 196 2>/dev/null    # code to close recursively
   else
-    (exit "$exit_code")           # preserve exit code if none provided
+    (builtin exit "$exit_code")   # preserve exit code if none provided
     builtin exit "$@" 2>/dev/null # passthrough argument to exit
   fi
 }
