Update source/.bashrc.d/30_functions/post-temp
Former-commit-id: e38b4e50667a552d4ef50f7c07cd7a45cad748ee
Former-commit-id: 777659e86a3f5b2d01c7f0a1c90d9b2bd83e0140
Former-commit-id: 9f21f94e824a445c227e29ddbd7983eaa208eb41

diff --git a/source/exact_dot_bashrc.d/exact_30_functions/post-temp b/source/exact_dot_bashrc.d/exact_30_functions/post-temp
--- a/source/exact_dot_bashrc.d/exact_30_functions/post-temp
+++ b/source/exact_dot_bashrc.d/exact_30_functions/post-temp
@@ -33,8 +33,6 @@ EOF
   local fx
   fx=$(which fx 2>/dev/null || printf '')
   if [ -z "$fx" ] && [ "$quiet" != "true" ]; then printf '%s\n' "$this: This script works much better with 'fx' installed." >&2; fi
-  local RED="\e[1;41m"
-  local BLANK="\e[0m"
 
   declare -i exitcode=0
   for file in "${args[@]}"; do
@@ -65,12 +63,11 @@ EOF
     if [ -z "$status" ] || [ -z "$url" ]; then
       message="$("$fx" '.message.toString()' <<<"$result" 2>/dev/null)"
       if [ -n "$message" ]; then
-        printf "$RED%s$BLANK\n" "$message" >&2
-      else
-        printf '%s\n' "$this: An unknown error occured" >&2
-      fi
+        printf "%s\n" "$this: $message" >&2
+      else printf '%s\n' "$this: An unknown error occured" >&2; fi
+      exitcode=1
     else
-      [ "$verbose" != true ] && printf '%s\n' "$status"
+      [ "$quiet" != true ] && printf '%s\n' "$status"
       printf '%s\n' "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
     fi
 
