Update source/.bashrc.d/30_functions/post-temp
Former-commit-id: 733a1c33e2948908f9f5d232f373e70821a6b66c
Former-commit-id: 5e672d740f99675e89bd76e62146451e2b97a03e
Former-commit-id: b92539f9fb28f1d43a69170d4812d38fa8129cad

diff --git a/source/exact_dot_bashrc.d/exact_30_functions/post-temp b/source/exact_dot_bashrc.d/exact_30_functions/post-temp
--- a/source/exact_dot_bashrc.d/exact_30_functions/post-temp
+++ b/source/exact_dot_bashrc.d/exact_30_functions/post-temp
@@ -6,53 +6,74 @@
 #
 #
 function post-temp() {
-  local verbose result status url message
+  local this='post-temp'
+  local verbose result status url message quiet
 
-  for arg; do #if any arg is --help
-    if [ "$arg" = "--help" ]; then
-      printf '%s\n' "post-temp [-v|--verbose] FILE"
-      printf '\n'
-      printf '%s\n' "Hosts a temporary file on the internet for 60 mins and returns the url."
+  local done='' args=() arg
+  for arg; do
+    # stop processing when hit --
+    if [ "$done" = true ]; then args+=("$arg") && continue; fi
+    case "$arg" in
+    --help | -h)
+      cat <<-EOF
+			$this [-v|--verbose] FILE
+
+			Hosts a temporary file on the internet for 60 mins and returns the url.
+EOF
       return 0
-    fi
+      ;;
+    -v | --verbose) verbose=true ;;                                            # Verbose option
+    -q | --quiet) quiet=true ;;                                                # Quiet option
+    --) done=true ;;                                                           # End of args. this is not one.
+    -*) printf '%s\n' "$this: invalid option -- '${arg#-}'" >&2 && return 2 ;; # Invalid -flag
+    *) args+=("$arg") ;;                                                       # Any other argument
+    esac
   done
 
-  if [ "$1" = -v ] || [ "$1" = --verbose ]; then verbose=true; fi
-  function is_verbose() { test -n "$verbose"; }
-  if is_verbose; then shift; fi # remove first arg if is --verbose
+  local fx
+  fx=$(which fx 2>/dev/null || printf '')
+  if [ -z "$fx" ] && [ "$quiet" != "true" ]; then printf '%s\n' "$this: This script works much better with 'fx' installed." >&2; fi
+  local RED="\e[1;41m"
+  local BLANK="\e[0m"
 
-  file=$1
-  if ! [[ -f "$file" ]]; then
-    printf "The path given is not a file\n"
-    return 2
-  fi
+  declare -i exitcode=0
+  for file in "${args[@]}"; do
+    if ! [[ -f "$file" ]]; then
+      printf "%s\n" "'$file' is not a file" >&2
+      exitcode=2 && continue
+    fi
 
-  result="$(curl -F "file=@$file" https://tmpfiles.org/api/v1/upload)"
-  # Example outputs:
-  # {"message": "server error"}
-  # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}
-  declare -i subshell_exit
-  (
-    if ! command -v 'fx' &>/dev/null; then return 1; fi
+    result="$(curl -sSfL -F "file=@$file" https://tmpfiles.org/api/v1/upload)" || {
+      printf '%s\n' 'Something went wrong during curl command. Aborting.' >&2
+      return 1 # Exit function, not loop
+    }
+    # Example outputs:
+    # {"message": "server error"}
+    # {"status":"success","data":{"url":"https://tmpfiles.org/######/file"}}
+
+    # If verbose, or fx not installed, print entire json
+    if [ "$verbose" = true ] || [ -z "$fx" ]; then
+      printf '%s\n' "$result"
+      [ -z "$fx" ] && continue # Stops loop here because fx is not installed
+    fi
 
     # Print the result thru fx to get the data
     # Already strings, if present, but trying to error
-    status="$(fx '.status.toString()' <<<"$result" 2>/dev/null)" &&
-      url="$(fx '.data.url.toString()' <<<"$result" 2>/dev/null)" && {
-      printf '%s\n' "$status" "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
-      return 0 # returns from subshell
-    }
-    # On error: (should've returned already on success)
-    RED="\e[1;41m"
-    BLANK="\e[0m"
-    message="$(fx '.message.toString()' <<<"$result" 2>/dev/null)" && {
-      printf "$RED%s$BLANK\n" "$message" >&2
-      return 1 # returns from subshell
-    }
-  )
-  subshell_exit=$?
-  # If verbose, or subshell failed (fx not installed or error returned), print entire json
-  if is_verbose || [ $subshell_exit -ne 0 ]; then
-    printf '%s\n' "$result"
-  fi
+    status="$("$fx" '.status.toString()' <<<"$result" 2>/dev/null)"
+    url="$("$fx" '.data.url.toString()' <<<"$result" 2>/dev/null)"
+
+    if [ -z "$status" ] || [ -z "$url" ]; then
+      message="$("$fx" '.message.toString()' <<<"$result" 2>/dev/null)"
+      if [ -n "$message" ]; then
+        printf "$RED%s$BLANK\n" "$message" >&2
+      else
+        printf '%s\n' "$this: An unknown error occured" >&2
+      fi
+    else
+      [ "$verbose" != true ] && printf '%s\n' "$status"
+      printf '%s\n' "${url/tmpfiles.org\//tmpfiles.org\/dl\/}"
+    fi
+
+  done
+  return $exitcode
 }
